// ── Feed store (Svelte 5 runes) ──────────────────────────────────────

import { SvelteMap } from "svelte/reactivity";
import { nextFeedId } from "./feed-id";
import {
  appendToolCall,
  applyToolResult,
  convertHistory,
  feedItemSignature,
  type BackgroundTurnState,
} from "./feed-items";
import type {
  ServerMessage,
  RecentMessage,
  FeedItem,
  DividerFeedItem,
  ToolCallState,
  ImageAttachment,
  FileAttachmentFeedItem,
  RecentHistorySegment,
  EpisodeHistorySegment,
  SessionUsageTotals,
} from "./types";

/**
 * Background messages at the head of a loaded history segment whose turn
 * began in older history, waiting for that history to decide whether they
 * are shown. `index` is where their items go in the feed.
 */
interface PendingHead {
  messages: RecentMessage[];
  index: number;
  /** The head of the recent segment (the one `reconcileRecent` rebuilds). */
  recent: boolean;
}

/** Existing items matched against reloaded history when reconciling. */
const RECONCILE_ANCHOR_ITEMS = 3;

/**
 * When the signed items of `fresh` begin with exactly `shown`, the index just
 * past the last of them; otherwise -1.
 */
function afterSignedPrefix(fresh: (string | null)[], shown: string[]): number {
  let matched = 0;
  for (let i = 0; i < fresh.length; i++) {
    if (matched === shown.length) return i;
    const sig = fresh[i];
    if (sig === null || sig === undefined) continue;
    if (sig !== shown[matched]) return -1;
    matched++;
  }
  return matched === shown.length ? fresh.length : -1;
}

/**
 * The index just past the last place the signed items of `fresh` end with
 * the run `anchor` (consecutive among signed items); 0 for an empty anchor,
 * -1 when it doesn't occur.
 */
function afterLastRun(fresh: (string | null)[], anchor: string[]): number {
  if (anchor.length === 0) return 0;
  for (let end = fresh.length - 1; end >= 0; end--) {
    if (fresh[end] == null) continue;
    let k = anchor.length - 1;
    for (let i = end; i >= 0 && k >= 0; i--) {
      const sig = fresh[i];
      if (sig == null) continue;
      if (sig !== anchor[k]) break;
      k--;
    }
    if (k < 0) return end + 1;
  }
  return -1;
}

/**
 * Whether history `recorded` holds the live turn: the turn's signed items are
 * non-empty and appear in order from the last place its first one does (a
 * turn is recorded whole, after anything older with the same text).
 */
function isSignedSubsequence(live: FeedItem[], recorded: FeedItem[]): boolean {
  const wanted = live.map(feedItemSignature).filter((sig) => sig !== null);
  if (wanted.length === 0) return false;
  const sigs = recorded.map(feedItemSignature);
  const start = sigs.lastIndexOf(wanted[0] ?? null);
  if (start < 0) return false;
  let next = 0;
  for (let i = start; i < sigs.length && next < wanted.length; i++) {
    if (sigs[i] === wanted[next]) next++;
  }
  return next === wanted.length;
}

const DAY_DIVIDER_FORMATTER = new Intl.DateTimeFormat(undefined, {
  month: "long",
  day: "numeric",
});

function dayKey(iso: string): string {
  // Timestamps are either "YYYY-MM-DD" or "YYYY-MM-DDTHH:MM". Slice to date.
  return iso.slice(0, 10);
}

function dayLabel(iso: string): string {
  const date = new Date(iso.length === 10 ? `${iso}T00:00` : iso);
  if (Number.isNaN(date.getTime())) return iso.slice(0, 10);
  return DAY_DIVIDER_FORMATTER.format(date);
}

/** A day-divider callback with its own memory of the last day seen. */
function dayDividerTracker(): (iso: string) => DividerFeedItem | null {
  let lastKey: string | null = null;
  return (iso) => {
    const key = dayKey(iso);
    const crossed = lastKey !== null && key !== lastKey;
    lastKey = key;
    return crossed
      ? { id: nextFeedId(), kind: "divider", variant: "day", label: dayLabel(iso) }
      : null;
  };
}

/** Manages the chat feed state and processes incoming server messages. */
export class FeedStore {
  feed = $state<FeedItem[]>([]);
  isProcessing = $state(false);
  /**
   * Correlation id of the turn currently in flight, or `null` when idle.
   * Set on `turn_started`, cleared on `turn_ended` — the only frame the
   * protocol guarantees closes every turn — so a stop request always has
   * the right id to target even if `isProcessing` cleared earlier via a
   * `response`/`error` frame.
   */
  activeTurnId = $state<string | null>(null);
  /**
   * `Date.now()` when the turn in flight started, or `null` when idle —
   * the running-turn indicator's live elapsed clock. Set on `turn_started`,
   * cleared on `turn_ended`, same lifecycle as `activeTurnId`.
   */
  turnStartedAt = $state<number | null>(null);
  /** Output tokens generated by every model call so far this turn. */
  turnOutputTokens = $state(0);
  /** Whether any model call so far this turn reported usage. */
  turnHasUsage = $state(false);
  /**
   * Cumulative session token totals for the chat footer, or `null` before
   * the first value arrives (a `turn_usage` frame, or the initial
   * `GET /api/usage` fetch on connect).
   */
  sessionUsage = $state<SessionUsageTotals | null>(null);
  /**
   * Whether the background post-turn observer/reflector cycle is
   * currently running (see `crate::gateway::post_turn` on the server) —
   * drives a quiet "updating memory…" indicator. Never blocks anything;
   * this work runs off the event loop, so a turn can start while it's
   * still in flight.
   */
  memoryWorking = $state(false);
  /** Same as `memoryWorking`, for the end-of-turn subconscious evaluation. */
  subconsciousWorking = $state(false);

  /**
   * Forget which background cycles are running. Called on disconnect: the
   * frame saying a cycle finished may never arrive, and an indicator stuck
   * on would claim work that already ended.
   */
  clearPostTurnActivity(): void {
    this.memoryWorking = false;
    this.subconsciousWorking = false;
  }
  oldestEpisodeCursor = $state<string | null>(null);
  hasMoreHistory = $state(false);
  isLoadingOlder = $state(false);

  /** Bumped whenever the whole feed is replaced from history. */
  generation = $state(0);
  /** Recent history has been loaded at least once. */
  historyLoaded = false;

  private pendingToolCalls = new SvelteMap<string, ToolCallState>();
  private lastLiveDayKey: string | null = null;
  private compressedMarkerInserted = false;
  private pendingHeads: PendingHead[] = [];
  /** Feed index where the recent segment's items begin. */
  private recentStart = 0;
  /** Cursor the recent segment pointed at when loaded. */
  private recentCursor: string | null = null;
  /** How the turn in progress at the recent segment's start was decided, once known. */
  private recentCarriedTurn: BackgroundTurnState | undefined;
  /** Episodes already in the feed, so a segment is never shown twice. */
  // eslint-disable-next-line svelte/prefer-svelte-reactivity -- bookkeeping only, never rendered
  private loadedEpisodes = new Set<string>();
  /**
   * Feed index where the turn in flight begins (its user message, or the
   * first item after `turn_started`), or `null` when idle. Its items are
   * live-only until the turn ends and history records them.
   */
  private turnStart: number | null = null;

  /** Dispatch a server message into the feed. */
  handleMessage(msg: ServerMessage): void {
    switch (msg.type) {
      case "turn_started":
        this.isProcessing = true;
        this.activeTurnId = msg.reply_to;
        this.turnStart ??= this.feed.length;
        this.turnStartedAt = Date.now();
        this.turnOutputTokens = 0;
        this.turnHasUsage = false;
        break;

      case "turn_ended":
        // Closes out turns that produce no response/error (e.g. zero-text
        // replies) — harmless no-op if isProcessing already cleared via
        // one of those paths.
        this.isProcessing = false;
        this.activeTurnId = null;
        this.turnStart = null;
        this.turnStartedAt = null;
        break;

      case "turn_usage":
        this.turnOutputTokens = msg.output_tokens;
        this.turnHasUsage = msg.has_usage;
        if (msg.session_totals) this.sessionUsage = msg.session_totals;
        break;

      case "post_turn_activity":
        if (msg.kind === "memory") this.memoryWorking = msg.active;
        else this.subconsciousWorking = msg.active;
        break;

      case "tool_call":
        appendToolCall(this.feed, this.pendingToolCalls, msg);
        break;

      case "tool_result":
        applyToolResult(this.pendingToolCalls, msg);
        break;

      case "response":
        this.isProcessing = false;
        if (msg.content) {
          this.feed.push({
            id: nextFeedId(),
            kind: "assistant",
            content: msg.content,
          });
        }
        break;

      case "broadcast_response":
        if (msg.content) {
          this.feed.push({
            id: nextFeedId(),
            kind: "assistant",
            content: msg.content,
          });
        }
        break;

      case "error":
        // Server error clears the thinking indicator. The notification
        // surface itself is dispatched by WsCoordinator before this runs.
        this.isProcessing = false;
        break;

      case "notice":
      case "reloading":
        // Surfaced by WsCoordinator; no chat-state side effect.
        break;

      case "inline_output":
        this.pushLocalSystem(msg.message);
        break;

      case "file_attachment": {
        const item: FileAttachmentFeedItem = {
          id: nextFeedId(),
          kind: "file-attachment",
          filename: msg.filename,
          mimeType: msg.mime_type,
          size: msg.size,
          url: msg.url,
          caption: msg.caption,
        };
        this.feed.push(item);
        this.isProcessing = false;
        break;
      }

      case "pong":
        break;

      case "session_started":
      case "session_state_changed":
      case "session_completed":
      case "session_turn_started":
      case "session_turn_ended":
      case "session_turn_usage":
      case "session_tool_call":
      case "session_tool_result":
      case "session_broadcast_response":
      case "session_response":
      case "session_error":
      case "session_message_to_main":
      case "session_message_delivered":
      case "session_stop_requested":
      case "session_command_failed":
        // Agent session activity belongs to the sessions surface, never
        // the main chat feed.
        break;

      case "artifact_updated":
      case "artifact_removed":
        // Workbench live reload belongs to the workbench views.
        break;

      case "workspace_changed":
      case "workspace_resync":
      case "workspace_watch_unavailable":
        // The change feed belongs to the open artifact and its bridge.
        break;
    }
  }

  /** Populate the feed from a Recent history segment. */
  loadHistory(segment: RecentHistorySegment): void {
    this.feed.length = 0;
    this.pendingToolCalls.clear();
    this.lastLiveDayKey = null;
    this.compressedMarkerInserted = false;
    this.loadedEpisodes.clear();
    this.oldestEpisodeCursor = segment.next_cursor;
    this.hasMoreHistory = segment.next_cursor !== null;
    this.recentStart = 0;
    this.turnStart = null;
    this.generation++;
    this.recentCursor = segment.next_cursor;
    // With no older history, a turn can't have begun before this segment.
    this.recentCarriedTurn = segment.next_cursor === null ? "hidden" : undefined;
    this.historyLoaded = true;

    const conversion = convertHistory(segment.messages, {
      mode: "main",
      dayDivider: (ts) => this.dayDividerFor(ts),
      carriedTurn: this.recentCarriedTurn,
    });
    this.pendingHeads = conversion.undecidedHead.length
      ? [{ messages: conversion.undecidedHead, index: 0, recent: true }]
      : [];
    for (const item of conversion.items) this.feed.push(item);
  }

  /**
   * Bring the recent part of the feed up to date with a freshly fetched
   * Recent segment, adding what the live connection missed (e.g. while it
   * was down). Lines history up with the settled messages shown (everything
   * before the turn in flight, which history doesn't hold until it ends);
   * returns `false` when they can't be lined up (history was compressed into
   * a new episode, or diverged), in which case the caller should
   * `reloadHistory`.
   */
  reconcileRecent(segment: RecentHistorySegment): boolean {
    if (!this.historyLoaded || segment.next_cursor !== this.recentCursor) return false;
    const fresh = convertHistory(segment.messages, {
      mode: "main",
      carriedTurn: this.recentCarriedTurn,
      // Replayed from the segment's start so dividers land where a fresh load
      // would put them; only those among the added items are kept.
      dayDivider: dayDividerTracker(),
    }).items;
    const liveStart = this.turnStart ?? this.feed.length;
    const shown: string[] = [];
    // Tool groups shown after the last signed item: history has them too.
    let trailingToolGroups = 0;
    for (const item of this.feed.slice(this.recentStart, liveStart)) {
      const sig = feedItemSignature(item);
      if (sig !== null) {
        shown.push(sig);
        trailingToolGroups = 0;
      } else if (item.kind === "tool-group") {
        trailingToolGroups++;
      }
    }
    const freshSigs = fresh.map(feedItemSignature);
    // Exactly what was shown, then more: the usual case. Failing that (the
    // live feed showed something history doesn't hold), line up on the last
    // few messages shown.
    let appendFrom = afterSignedPrefix(freshSigs, shown);
    if (appendFrom < 0) appendFrom = afterLastRun(freshSigs, shown.slice(-RECONCILE_ANCHOR_ITEMS));
    if (appendFrom < 0) return false;
    while (trailingToolGroups > 0 && fresh[appendFrom]?.kind === "tool-group") {
      appendFrom++;
      trailingToolGroups--;
    }
    this.placeRecorded(fresh.slice(appendFrom), liveStart);
    this.syncDayKey(segment);
    return true;
  }

  /**
   * Replace the feed with a freshly fetched Recent segment, keeping the turn
   * in flight: its live items are put back after the history unless history
   * already records the turn (it ended while disconnected).
   */
  reloadHistory(segment: RecentHistorySegment): void {
    const liveStart = this.turnStart;
    const live = liveStart === null ? [] : this.feed.slice(liveStart);
    const pendingTools = [...this.pendingToolCalls];
    this.loadHistory(segment);
    if (liveStart === null) return;
    const recent = this.feed.slice(this.recentStart);
    if (isSignedSubsequence(live, recent)) {
      this.endLiveTurn();
      return;
    }
    this.turnStart = this.feed.length;
    for (const item of live) this.feed.push(item);
    for (const [id, call] of pendingTools) this.pendingToolCalls.set(id, call);
  }

  /**
   * Prepend an episode segment to the top of the feed.
   *
   * Inserts an `ep-NNN · date` divider above the episode's messages. On the
   * first prepend, also inserts a `compressed-marker` between the episode
   * block and the already-present live messages so the user sees where
   * the observer cut.
   */
  prependEpisode(segment: EpisodeHistorySegment): void {
    if (this.loadedEpisodes.has(segment.episode_id)) return;
    this.loadedEpisodes.add(segment.episode_id);

    const conversion = convertHistory(segment.messages, { mode: "main" });
    if (conversion.endTurn !== "unknown") this.resolvePendingHeads(conversion.endTurn);

    const block: FeedItem[] = [
      {
        id: nextFeedId(),
        kind: "divider",
        variant: "episode",
        label: `${segment.episode_id} · ${segment.date}`,
      } satisfies DividerFeedItem,
      ...conversion.items,
    ];

    if (!this.compressedMarkerInserted) {
      block.push({ id: nextFeedId(), kind: "compressed-marker" });
      this.compressedMarkerInserted = true;
    }

    this.feed.splice(0, 0, ...block);
    this.recentStart += block.length;
    if (this.turnStart !== null) this.turnStart += block.length;
    for (const head of this.pendingHeads) head.index += block.length;
    if (conversion.undecidedHead.length) {
      // Just below this episode's divider.
      this.pendingHeads.push({ messages: conversion.undecidedHead, index: 1, recent: false });
    }
    this.oldestEpisodeCursor = segment.next_cursor;
    this.hasMoreHistory = segment.next_cursor !== null;
  }

  /**
   * Push a client-only system message into the feed for inline rendering.
   * Used by slash commands like `/help` and `/status`, and by inbound
   * `inline_output` server messages (e.g. `/context` results). These items
   * never round-trip to history and vanish on reload.
   */
  pushLocalSystem(content: string): void {
    this.feed.push({ id: nextFeedId(), kind: "local-system", content });
  }

  /**
   * Add a message a session sent the main agent (its relayed result, or a
   * `message_agent` call), as it arrives live.
   */
  pushAgentMessage(from: string, runId: string, content: string, category: string | null): void {
    this.feed.push({ id: nextFeedId(), kind: "agent-message", from, category, content, runId });
  }

  /**
   * Seed the chat footer's cumulative totals from `GET /api/usage`, called
   * once on connect/reconnect so the footer renders correctly before the
   * next model call rather than starting blank.
   */
  setInitialUsage(totals: SessionUsageTotals): void {
    this.sessionUsage = totals;
  }

  /** Add a user message to the feed. */
  pushUserMessage(content: string, images?: ImageAttachment[]): void {
    // Live user messages carry an implicit "now" timestamp — inject a day
    // divider if the calendar day has rolled over since the last live entry.
    // eslint-disable-next-line svelte/prefer-svelte-reactivity
    const nowIso = new Date().toISOString();
    this.maybePushDayDivider(nowIso);
    this.turnStart ??= this.feed.length;
    this.feed.push({ id: nextFeedId(), kind: "user", content, images });
    this.isProcessing = true;
  }

  // ── Private ──────────────────────────────────────────────────────────

  /**
   * Older history decided the turn that pending heads continue: insert them
   * if it's shown, drop them if not.
   */
  private resolvePendingHeads(turn: "shown" | "hidden"): void {
    // Highest index first, so inserting doesn't shift the ones still to go.
    const heads = [...this.pendingHeads].sort((a, b) => b.index - a.index);
    this.pendingHeads = [];
    for (const head of heads) {
      if (head.recent) this.recentCarriedTurn = turn;
      if (turn === "hidden") continue;
      const items = convertHistory(head.messages, { mode: "main", carriedTurn: "shown" }).items;
      this.feed.splice(head.index, 0, ...items);
      if (head.index < this.recentStart) this.recentStart += items.length;
      if (this.turnStart !== null && head.index <= this.turnStart) {
        this.turnStart += items.length;
      }
    }
  }

  /**
   * Add history items newer than everything settled in the feed. If they
   * include the turn in flight (it ended while disconnected), they replace
   * its live items and the turn is closed; otherwise they go before it.
   */
  private placeRecorded(recorded: FeedItem[], liveStart: number): void {
    const live = this.feed.slice(liveStart);
    if (this.turnStart !== null && isSignedSubsequence(live, recorded)) {
      this.feed.splice(liveStart, live.length, ...recorded);
      this.endLiveTurn();
      return;
    }
    this.feed.splice(liveStart, 0, ...recorded);
    if (this.turnStart !== null) this.turnStart += recorded.length;
  }

  /** The turn in flight is over (history records it); clear its live state. */
  private endLiveTurn(): void {
    this.turnStart = null;
    this.isProcessing = false;
    this.activeTurnId = null;
    this.pendingToolCalls.clear();
  }

  /** Continue live day dividers from the newest message in `segment`. */
  private syncDayKey(segment: RecentHistorySegment): void {
    const last = segment.messages[segment.messages.length - 1];
    if (last?.timestamp) this.lastLiveDayKey = dayKey(last.timestamp);
  }

  private dayDividerFor(iso: string): DividerFeedItem | null {
    const key = dayKey(iso);
    const crossed = this.lastLiveDayKey !== null && key !== this.lastLiveDayKey;
    this.lastLiveDayKey = key;
    return crossed
      ? { id: nextFeedId(), kind: "divider", variant: "day", label: dayLabel(iso) }
      : null;
  }

  private maybePushDayDivider(iso: string): void {
    const divider = this.dayDividerFor(iso);
    if (divider) this.feed.push(divider);
  }
}
