// ── Agent sessions store (Svelte 5 runes) ────────────────────────────
//
// Owns everything the sessions sidebar and session view show: the listing
// from `GET /api/sessions`, live `session_*` WebSocket frames, the run being
// viewed, and the sidebar's commands (message, stop). Session frames are
// routed here by the WebSocket coordinator and never reach the main
// `FeedStore` — the one crossover is a session's message to the main agent,
// which is handed back to the coordinator to show in the main chat.

import { SvelteMap, SvelteSet } from "svelte/reactivity";
import {
  ApiError,
  fetchOutboundA2aTasks,
  fetchSessionTranscript,
  fetchSessions,
  stopOutboundA2aTask,
  stopWatchingOutboundA2aTask,
} from "./api";
import { userErrorMessage } from "./errors";
import { nextFeedId } from "./feed-id";
import { appendToolCall, applyToolResult, convertHistoryMessages } from "./feed-items";
import { notifications } from "./notifications.svelte";
import { router } from "./router.svelte";
import { SESSION_CATEGORIES, deliveryOutcomeText, runOutcomeText } from "./session-format";
import type {
  ClientMessage,
  FeedItem,
  OutboundA2aTaskSummary,
  ServerMessage,
  SessionCategory,
  SessionRunStatus,
  SessionSummary,
  ToolCallState,
} from "./types";

/** Every server frame that belongs to the sessions surface. */
export type SessionFrame = Extract<ServerMessage, { type: `session_${string}` }>;

/** Frames that describe activity inside one run. */
type RunFrame = Extract<SessionFrame, { run_id: string }>;

export function isSessionFrame(msg: ServerMessage): msg is SessionFrame {
  return msg.type.startsWith("session_");
}

/** Completed runs fetched per page, per category. */
const PAGE_SIZE = 25;

/** Coalesces bursts of frames for unknown runs into one listing refresh. */
const REFRESH_DEBOUNCE_MS = 250;

// ── Session view ─────────────────────────────────────────────────────

/** One run shown in the main pane: its transcript plus live frames. */
export class SessionView {
  runId = $state<string>("");
  summary = $state<SessionSummary | null>(null);
  items = $state<FeedItem[]>([]);
  loading = $state(true);
  loadError = $state<string | null>(null);
  /** A stop was requested and the run hasn't finished yet. */
  stopRequested = $state(false);
  /**
   * `Date.now()` when the run's turn in flight started, or `null` when
   * idle — this view's own running-turn indicator clock, the session
   * counterpart of the main chat's `turnStartedAt`.
   */
  turnStartedAt = $state<number | null>(null);
  /** Output tokens generated by every model call so far this turn. */
  turnOutputTokens = $state(0);
  /** Whether any model call so far this turn reported usage. */
  turnHasUsage = $state(false);
  /**
   * Set when a message from this view started (or will start) a new run at
   * the same address; the view follows that run when it appears.
   */
  followAddress: string | null = null;

  private pendingTools = new SvelteMap<string, ToolCallState>();
  /** Frames for the run being loaded that arrived while its transcript was loading. */
  private buffered: RunFrame[] = [];
  /** Identifies the latest load; an older one finishing late is ignored. */
  private loadToken = 0;
  /** Feed index where the turn in flight began (its owner message, or the
   * first item after `session_turn_started`), for tagging it with the
   * turn id once the turn ends — the session counterpart of the main
   * chat's `FeedStore.turnStart`. */
  private turnStart: number | null = null;

  constructor(runId: string, summary: SessionSummary | null) {
    this.runId = runId;
    this.summary = summary;
  }

  /** Load (or reload) the current run's transcript, then replay frames that raced it. */
  async load(): Promise<void> {
    const token = ++this.loadToken;
    const runId = this.runId;
    this.loading = true;
    this.loadError = null;
    // Frames already buffered for this run may postdate what the transcript
    // holds; frames for any other run no longer belong to this view.
    this.buffered = this.buffered.filter((frame) => frame.run_id === runId);
    let transcript;
    try {
      transcript = await fetchSessionTranscript(runId);
    } catch (err) {
      if (token !== this.loadToken) return;
      this.loadError = userErrorMessage(err, {
        action: "Couldn't load this session's transcript.",
        notFound: "Its history isn't available. It may be from before a restart.",
      });
      this.buffered = [];
      this.loading = false;
      return;
    }
    if (token !== this.loadToken) return;
    this.summary = transcript.session;
    this.pendingTools.clear();
    this.items = convertHistoryMessages(transcript.messages, { mode: "session" });
    this.loading = false;
    const raced = this.buffered;
    this.buffered = [];
    for (const frame of raced) this.applyFrame(frame, { dedupe: true });
  }

  /**
   * Apply a live frame for this run. `dedupe` is set when replaying frames
   * that arrived during the transcript fetch, which may already be in it.
   */
  applyFrame(frame: RunFrame, opts: { dedupe: boolean } = { dedupe: false }): void {
    if (this.loading) {
      this.buffered.push(frame);
      return;
    }
    switch (frame.type) {
      case "session_tool_call":
        if (opts.dedupe && this.findToolCall(frame.id)) return;
        appendToolCall(this.items, this.pendingTools, frame);
        break;
      case "session_tool_result": {
        if (!this.pendingTools.has(frame.tool_call_id)) {
          const existing = this.findToolCall(frame.tool_call_id);
          if (existing && existing.result === undefined) {
            this.pendingTools.set(frame.tool_call_id, existing);
          }
        }
        applyToolResult(this.pendingTools, frame);
        break;
      }
      case "session_broadcast_response":
      case "session_response":
        if (!frame.content) return;
        if (opts.dedupe && this.lastAssistantContent() === frame.content) return;
        this.items.push({ id: nextFeedId(), kind: "assistant", content: frame.content });
        break;
      case "session_error":
        this.pushStatus("error", frame.message, frame.details ?? undefined);
        break;
      case "session_completed":
        this.stopRequested = false;
        this.pushStatus(
          frame.status === "failed" ? "error" : "info",
          runOutcomeText(frame.status, frame.error),
        );
        break;
      case "session_turn_started":
        this.turnStart ??= this.items.length;
        this.turnStartedAt = Date.now();
        this.turnOutputTokens = 0;
        this.turnHasUsage = false;
        break;
      case "session_turn_ended":
        this.tagTurnStart(frame.turn_id);
        this.turnStart = null;
        this.turnStartedAt = null;
        break;
      case "session_turn_usage":
        this.turnOutputTokens = frame.output_tokens;
        this.turnHasUsage = frame.has_usage;
        if (frame.session_totals && this.summary) this.summary.usage = frame.session_totals;
        break;
      case "session_state_changed":
      case "session_message_to_main":
        break;
    }
  }

  pushStatus(tone: "info" | "error", content: string, details?: string): void {
    this.items.push({ id: nextFeedId(), kind: "status", tone, content, details });
  }

  pushOwnerMessage(content: string): void {
    this.turnStart ??= this.items.length;
    this.items.push({ id: nextFeedId(), kind: "user", content });
  }

  /** Tag the user message that started the turn just ending with its turn
   * id, so the view can offer "Undo this turn" on it — see
   * `FeedStore.tagTurnStart`'s main-chat counterpart. */
  private tagTurnStart(turnId: string): void {
    if (this.turnStart === null) return;
    const item = this.items[this.turnStart];
    if (item?.kind === "user") {
      item.turn = { turnId, changed: null };
    }
  }

  /**
   * Continue this view in a new run of the same session. Mid-load, the
   * pending load is superseded by one for the new run, whose transcript
   * holds everything that started it.
   */
  follow(summary: SessionSummary): void {
    this.followAddress = null;
    this.runId = summary.run_id;
    this.summary = summary;
    this.stopRequested = false;
    this.pendingTools.clear();
    if (this.loading) {
      void this.load();
      return;
    }
    this.items.push({ id: nextFeedId(), kind: "divider", variant: "day", label: "new run" });
  }

  private findToolCall(id: string): ToolCallState | undefined {
    for (const item of this.items) {
      if (item.kind !== "tool-group") continue;
      const call = item.calls.find((c) => c.id === id);
      if (call) return call;
    }
    return undefined;
  }

  private lastAssistantContent(): string | null {
    for (let i = this.items.length - 1; i >= 0; i--) {
      const item = this.items[i];
      if (item?.kind === "assistant") return item.content;
    }
    return null;
  }
}

// ── Completed runs (one category) ───────────────────────────────────

/**
 * The completed runs of one category loaded so far, paged from the server
 * independently of the other categories.
 */
export class CompletedRuns {
  /** Runs loaded so far, newest first. */
  runs = $state<SessionSummary[]>([]);
  /** Cursor for the next page, or `null` on the last. */
  nextCursor = $state<string | null>(null);
  loadingMore = $state(false);

  constructor(readonly category: SessionCategory) {}

  /** Load the next page of this category's completed runs. */
  async loadMore(): Promise<void> {
    const cursor = this.nextCursor;
    if (!cursor || this.loadingMore) return;
    this.loadingMore = true;
    try {
      const page = await fetchSessions({
        category: this.category,
        before: cursor,
        limit: PAGE_SIZE,
      });
      // eslint-disable-next-line svelte/prefer-svelte-reactivity -- non-reactive scratch
      const known = new Set(this.runs.map((s) => s.run_id));
      this.runs.push(...page.completed.filter((s) => !known.has(s.run_id)));
      this.nextCursor = page.next_cursor;
    } catch (err) {
      notifications.surface(
        "error",
        userErrorMessage(err, { action: `Couldn't load more finished ${this.category} sessions.` }),
      );
    } finally {
      this.loadingMore = false;
    }
  }

  /** Put a run that just finished at the top. */
  prepend(run: SessionSummary): void {
    this.runs = [run, ...this.runs.filter((s) => s.run_id !== run.run_id)];
  }

  /**
   * Replace the head of the list with a fresh first page, keeping runs
   * paged in beyond it. Runs are matched by id and kept only if they sort
   * after the page's last run in the server's order (newest start first,
   * ties broken by run id), so runs sharing a start time survive.
   */
  mergeFirstPage(first: SessionSummary[], firstCursor: string | null): void {
    const oldCursor = this.nextCursor;
    const last = first[first.length - 1];
    if (firstCursor === null || !last || this.runs.length <= first.length) {
      this.runs = first;
      this.nextCursor = firstCursor;
      return;
    }
    // eslint-disable-next-line svelte/prefer-svelte-reactivity -- non-reactive scratch
    const inFirst = new Set(first.map((s) => s.run_id));
    const tail = this.runs.filter(
      (s) => !inFirst.has(s.run_id) && compareRunsNewestFirst(s, last) > 0,
    );
    this.runs = [...first, ...tail];
    this.nextCursor = tail.length ? oldCursor : firstCursor;
  }
}

// ── Sessions store ───────────────────────────────────────────────────

interface PendingCommand {
  kind: "message" | "stop";
  address: string;
}

export interface SessionsStoreDeps {
  /** Send a client frame over the WebSocket. */
  send: (msg: ClientMessage) => void;
  /** Show a session's message to the main agent in the main chat. */
  pushToMain: (from: string, runId: string, content: string, category: string | null) => void;
}

export class SessionsStore {
  /** Live runs (forking, running, idle, completing), newest first. */
  live = $state<SessionSummary[]>([]);
  /** Completed runs loaded so far, per category. */
  readonly completed: Record<SessionCategory, CompletedRuns> = {
    external: new CompletedRuns("external"),
    scheduled: new CompletedRuns("scheduled"),
    spawned: new CompletedRuns("spawned"),
    artifact: new CompletedRuns("artifact"),
  };
  /** The listing has loaded at least once. */
  loaded = $state(false);
  listError = $state<string | null>(null);
  /** How runs ended, for those that finished while this page was open. */
  outcomes = new SvelteMap<
    string,
    { status: SessionRunStatus; error: string | null; errorDetails: string | null }
  >();
  /** Latest error per live run, flagged in the sidebar. */
  errors = new SvelteMap<string, string>();
  /**
   * Addresses with a stop requested but not yet resolved, for a row's own
   * stop button (in the sidebar or an artifact's activity panel) to disable
   * itself and show "Stopping…" without needing a `SessionView`.
   */
  stopping = new SvelteSet<string>();
  /** Open tasks the agent sent to remote agents, newest first. */
  outbound = $state<OutboundA2aTaskSummary[]>([]);
  /** Why the outbound task list couldn't load, if it couldn't. */
  outboundError = $state<string | null>(null);
  /** Outbound task ids with a stop (or stop-watching) request in flight. */
  outboundStopping = new SvelteSet<string>();
  /**
   * Outbound tasks whose stop failed because their agent couldn't be
   * reached, with the message to show — their row offers stop-watching.
   */
  outboundUnreachable = new SvelteMap<string, string>();
  /** The run shown in the main pane, if any. */
  view = $state<SessionView | null>(null);
  /** Clock for elapsed times; ticked by the app while sessions are live. */
  now = $state(Date.now());

  // eslint-disable-next-line svelte/prefer-svelte-reactivity -- bookkeeping only, never rendered
  private pending = new Map<string, PendingCommand>();
  private commandCounter = 0;
  private refreshing = false;
  private refreshAgain = false;
  private refreshTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(private readonly deps: SessionsStoreDeps) {}

  // ── Listing ──────────────────────────────────────────────────────

  /**
   * Reload live sessions and the first page of each category's completed
   * runs. Completed runs already paged in beyond the first page are kept,
   * so a refresh doesn't collapse the list the user is reading.
   */
  async refresh(): Promise<void> {
    void this.refreshOutbound();
    if (this.refreshing) {
      this.refreshAgain = true;
      return;
    }
    this.refreshing = true;
    try {
      // One request per category, so each category's finished runs page on
      // their own; together the pages' live lists cover every live session.
      const pages = await Promise.all(
        SESSION_CATEGORIES.map((category) => fetchSessions({ category, limit: PAGE_SIZE })),
      );
      this.live = pages.flatMap((page) => page.live).sort(compareRunsNewestFirst);
      SESSION_CATEGORIES.forEach((category, i) => {
        const page = pages[i];
        if (page) this.completed[category].mergeFirstPage(page.completed, page.next_cursor);
      });
      this.listError = null;
      this.loaded = true;
      this.syncViewSummary();
    } catch (err) {
      this.listError = userErrorMessage(err, { action: "Couldn't load sessions." });
    } finally {
      this.refreshing = false;
    }
    if (this.refreshAgain) {
      this.refreshAgain = false;
      await this.refresh();
    }
  }

  /** Reload the tasks sent to remote agents. Failure only affects that list. */
  async refreshOutbound(): Promise<void> {
    try {
      this.outbound = await fetchOutboundA2aTasks();
      this.outboundError = null;
    } catch (err) {
      this.outboundError = userErrorMessage(err, {
        action: "Couldn't load the tasks sent to other agents.",
      });
    }
  }

  /** Resynchronize after the WebSocket (re)connects: frames may have been missed. */
  resync(): void {
    void this.refresh();
    const view = this.view;
    if (view && !view.loading && view.summary?.state !== "completed") void view.load();
  }

  findRun(runId: string): SessionSummary | undefined {
    return (
      this.live.find((s) => s.run_id === runId) ??
      this.completedRuns().find((s) => s.run_id === runId)
    );
  }

  /** The newest known run at `address`, live runs first. */
  findByAddress(address: string): SessionSummary | undefined {
    return (
      this.live.find((s) => s.address === address) ??
      this.completedRuns()
        .filter((s) => s.address === address)
        .sort(compareRunsNewestFirst)[0]
    );
  }

  // ── Navigation ───────────────────────────────────────────────────

  /** Navigate to a run, showing it in the main pane. */
  openRun(runId: string): void {
    router.openSession(runId);
  }

  /**
   * Put a run in the main pane. Called when the location changes; anything
   * that wants to show a run navigates with `openRun` instead.
   */
  showRun(runId: string): void {
    if (this.view?.runId === runId) return;
    const view = new SessionView(runId, this.findRun(runId) ?? null);
    this.view = view;
    void view.load();
  }

  /**
   * Show a session by address: `runId` when known, else its newest run
   * (live first), looked up on the server if it isn't loaded.
   */
  async openAddress(address: string, runId: string | null): Promise<void> {
    if (runId) {
      this.openRun(runId);
      return;
    }
    const known = this.findByAddress(address);
    if (known) {
      this.openRun(known.run_id);
      return;
    }
    try {
      const page = await fetchSessions({ address, limit: 1 });
      const run = page.live[0] ?? page.completed[0];
      if (run) {
        this.openRun(run.run_id);
      } else {
        notifications.surface("error", `There's no record of the session ${address}.`);
      }
    } catch (err) {
      notifications.surface(
        "error",
        userErrorMessage(err, { action: `Couldn't open the session ${address}.` }),
      );
    }
  }

  /** Take the run out of the main pane. Called when the location changes. */
  closeView(): void {
    this.view = null;
  }

  // ── Commands ─────────────────────────────────────────────────────

  /** Message the session at `address` as the owner. */
  sendMessage(address: string, content: string): void {
    const id = this.commandId();
    this.pending.set(id, { kind: "message", address });
    this.deps.send({ type: "session_send_message", id, address, content });
    const view = this.viewFor(address);
    view?.pushOwnerMessage(content);
  }

  /** Stop the session at `address`. */
  stop(address: string): void {
    const id = this.commandId();
    this.pending.set(id, { kind: "stop", address });
    this.stopping.add(address);
    this.deps.send({ type: "session_stop", id, address });
    const view = this.viewFor(address);
    if (view) view.stopRequested = true;
  }

  /** Ask an outbound task's remote agent to cancel it. */
  async stopOutbound(taskId: string): Promise<void> {
    if (this.outboundStopping.has(taskId)) return;
    this.outboundStopping.add(taskId);
    try {
      this.upsertOutbound(await stopOutboundA2aTask(taskId));
      this.outboundUnreachable.delete(taskId);
    } catch (err) {
      const unreachable = unreachableAgentMessage(err);
      if (unreachable) {
        this.outboundUnreachable.set(taskId, unreachable);
        return;
      }
      notifications.surface(
        "error",
        userErrorMessage(err, { action: "Couldn't stop the task.", notFound: "It already ended." }),
      );
      if (err instanceof ApiError && err.status === 404) void this.refreshOutbound();
    } finally {
      this.outboundStopping.delete(taskId);
    }
  }

  /** Close an outbound task locally, for one whose agent can't be reached. */
  async stopWatchingOutbound(taskId: string): Promise<void> {
    if (this.outboundStopping.has(taskId)) return;
    this.outboundStopping.add(taskId);
    try {
      this.upsertOutbound(await stopWatchingOutboundA2aTask(taskId));
    } catch (err) {
      notifications.surface(
        "error",
        userErrorMessage(err, {
          action: "Couldn't stop watching the task.",
          notFound: "It already ended.",
        }),
      );
      if (err instanceof ApiError && err.status === 404) void this.refreshOutbound();
    } finally {
      this.outboundStopping.delete(taskId);
    }
  }

  // ── Frames ───────────────────────────────────────────────────────

  handleFrame(frame: SessionFrame): void {
    switch (frame.type) {
      case "session_outbound_a2a_task":
        this.upsertOutbound(frame.task);
        return;
      case "session_started":
        this.handleStarted(frame.session);
        return;
      case "session_message_delivered":
      case "session_stop_requested":
      case "session_command_failed":
        this.handleCommandReply(frame);
        return;
      case "session_state_changed":
      case "session_completed":
      case "session_turn_started":
      case "session_turn_ended":
      case "session_turn_usage":
      case "session_tool_call":
      case "session_tool_result":
      case "session_broadcast_response":
      case "session_response":
      case "session_error":
      case "session_message_to_main":
        this.handleRunFrame(frame);
        return;
    }
  }

  private handleStarted(session: SessionSummary): void {
    this.live = [session, ...this.live.filter((s) => s.run_id !== session.run_id)];
    const view = this.view;
    if (view?.followAddress === session.address) {
      view.follow(session);
      router.replaceSession(session.run_id);
    }
  }

  private handleRunFrame(frame: RunFrame): void {
    const live = this.live.find((s) => s.run_id === frame.run_id);
    if (!live) this.scheduleRefresh();

    switch (frame.type) {
      case "session_state_changed":
        if (live) live.state = frame.state;
        break;
      case "session_completed":
        this.handleCompleted(frame, live);
        break;
      case "session_error":
        this.errors.set(frame.run_id, frame.message);
        break;
      case "session_turn_usage":
        if (live && frame.session_totals) live.usage = frame.session_totals;
        break;
      case "session_message_to_main":
        this.deps.pushToMain(
          frame.address,
          frame.run_id,
          frame.content,
          (live ?? this.findByAddress(frame.address))?.category ?? null,
        );
        break;
      case "session_turn_started":
      case "session_turn_ended":
      case "session_tool_call":
      case "session_tool_result":
      case "session_broadcast_response":
      case "session_response":
        break;
    }

    const view = this.view;
    if (view?.runId === frame.run_id) {
      view.applyFrame(frame);
      this.syncViewSummary();
    }
  }

  private handleCompleted(
    frame: Extract<SessionFrame, { type: "session_completed" }>,
    live: SessionSummary | undefined,
  ): void {
    this.outcomes.set(frame.run_id, {
      status: frame.status,
      error: frame.error,
      errorDetails: frame.error_details,
    });
    this.errors.delete(frame.run_id);
    if (!live) return;
    this.stopping.delete(live.address);
    this.live = this.live.filter((s) => s.run_id !== frame.run_id);
    const finished: SessionSummary = {
      ...$state.snapshot(live),
      state: "completed",
      // eslint-disable-next-line svelte/prefer-svelte-reactivity -- a one-off timestamp
      completed_at: new Date().toISOString(),
      episode_id: frame.episode_id,
    };
    this.completed[finished.category].prepend(finished);
  }

  private handleCommandReply(
    frame: Extract<
      SessionFrame,
      {
        type: "session_message_delivered" | "session_stop_requested" | "session_command_failed";
      }
    >,
  ): void {
    const command = this.pending.get(frame.id);
    this.pending.delete(frame.id);
    const view = this.viewFor(frame.address);

    switch (frame.type) {
      case "session_message_delivered": {
        const text = deliveryOutcomeText(frame.outcome);
        if (view) {
          view.pushStatus("info", text);
          if (frame.outcome !== "live") view.followAddress = frame.address;
        } else {
          notifications.surface("notice", `${frame.address}: ${text}`);
        }
        break;
      }
      case "session_stop_requested":
        if (view) view.pushStatus("info", "Stopping this session…");
        break;
      case "session_command_failed": {
        const action = command?.kind === "stop" ? "Couldn't stop it" : "Couldn't send it";
        if (command?.kind === "stop") this.stopping.delete(frame.address);
        if (view) {
          if (command?.kind === "stop") view.stopRequested = false;
          view.pushStatus("error", `${action}. ${frame.message}`);
        } else {
          notifications.surface("error", `${frame.address}: ${frame.message}`);
        }
        break;
      }
    }
  }

  // ── Private ──────────────────────────────────────────────────────

  /** Put a task's latest state in the list, or take it out once it ended. */
  private upsertOutbound(task: OutboundA2aTaskSummary): void {
    const rest = this.outbound.filter((t) => t.task_id !== task.task_id);
    if (!task.open) {
      this.outbound = rest;
      this.outboundUnreachable.delete(task.task_id);
      return;
    }
    if (!task.unreachable_since) this.outboundUnreachable.delete(task.task_id);
    this.outbound = [task, ...rest].sort(
      (a, b) => Date.parse(b.started_at) - Date.parse(a.started_at),
    );
  }

  /** Every completed run loaded so far, across categories. */
  private completedRuns(): SessionSummary[] {
    return SESSION_CATEGORIES.flatMap((category) => this.completed[category].runs);
  }

  private viewFor(address: string): SessionView | null {
    const view = this.view;
    return view?.summary?.address === address ? view : null;
  }

  private commandId(): string {
    this.commandCounter++;
    return `session-cmd-${this.commandCounter}`;
  }

  /** Keep the viewed run's header in step with the listing. */
  private syncViewSummary(): void {
    const view = this.view;
    if (!view) return;
    const known = this.findRun(view.runId);
    if (!known || !view.summary) return;
    view.summary.state = known.state;
    view.summary.completed_at = known.completed_at;
    view.summary.episode_id = known.episode_id;
  }

  private scheduleRefresh(): void {
    if (this.refreshTimer) return;
    this.refreshTimer = setTimeout(() => {
      this.refreshTimer = null;
      void this.refresh();
    }, REFRESH_DEBOUNCE_MS);
  }
}

/**
 * The server's explanation when an outbound task's stop failed because its
 * agent couldn't be reached (`502` with code `unreachable`), else `null`.
 */
export function unreachableAgentMessage(err: unknown): string | null {
  if (!(err instanceof ApiError) || err.status !== 502) return null;
  try {
    const body: unknown = JSON.parse(err.body);
    if (
      typeof body === "object" &&
      body !== null &&
      "code" in body &&
      body.code === "unreachable" &&
      "error" in body &&
      typeof body.error === "string"
    ) {
      return body.error;
    }
  } catch {
    // Not our JSON error body (a proxy's error page); handled as a plain failure.
  }
  return null;
}

/**
 * Order runs as the server lists completed runs: newest start first, then
 * run id descending. Negative when `a` comes before `b`.
 */
export function compareRunsNewestFirst(a: SessionSummary, b: SessionSummary): number {
  const byStart = Date.parse(b.started_at) - Date.parse(a.started_at);
  if (byStart !== 0) return byStart;
  if (a.run_id === b.run_id) return 0;
  return a.run_id > b.run_id ? -1 : 1;
}
