// ── Protocol types (generated by ts-rs from Rust source) ─────────────

import type {
  ImageAttachment as _ImageAttachment,
  SessionSummary as _SessionSummary,
  RepoStats as _RepoStats,
} from "./generated/protocol";
export type {
  ClientMessage,
  ServerMessage,
  ImageAttachment,
  SessionCategory,
  SessionCommandErrorCode,
  SessionDeliveryOutcome,
  SessionListResponse,
  SessionRunStatus,
  SessionState,
  SessionSummary,
  SessionUsageTotals,
  WorkbenchInfo,
  WorkbenchRelayOrigins,
  ArtifactSummary,
  WorkspaceChange,
  WorkspaceChangeKind,
  WorkspaceResyncReason,
  CheckpointSummary,
  CheckpointPage,
  CheckpointDetail,
  ChangedPath,
  ChangeKind,
  RepoKind,
  RepoStats,
  RestoreOutcome,
  UndoOutcome,
  CheckpointTrigger,
  PulseOverlap,
  PulseInfo,
  ActionInfo,
  ScheduledCurrentRun,
  ScheduledRunOutcome,
} from "./generated/protocol";

// Local aliases for use within this file
type ImageAttachment = _ImageAttachment;
type SessionSummary = _SessionSummary;
type RepoStats = _RepoStats;

// ── Chat history ─────────────────────────────────────────────────────

export interface ToolCallRecord {
  id: string;
  name: string;
  /**
   * Deliberately `unknown`: the wire shape depends on the source. History
   * (`/api/chat/history`) serializes this from a Rust `serde_json::Value`, so
   * it arrives as an **object**; other paths have carried it as a JSON
   * **string**. Typing it as `string` previously invited a bare
   * `JSON.parse(...)`, which throws `SyntaxError` on an object and took out
   * the whole feed render.
   *
   * Keep this `unknown` so the compiler forces every reader through
   * `normalizeToolArgs()` instead of assuming a shape.
   */
  arguments: unknown;
}

/** Person behind a user message that arrived on a chat interface. */
export interface MessageSender {
  name: string;
  id: string;
  interface: string;
  location?: string;
}

export interface RecentMessage {
  role: "user" | "assistant" | "tool" | "system";
  content: string;
  tool_calls?: ToolCallRecord[];
  tool_call_id?: string;
  timestamp: string;
  visibility: "user" | "background";
  sender?: MessageSender;
  /** The agent that sent this message, for one agent's message to another. */
  agent_sender?: AgentSender;
}

/** The agent behind a message one agent sent another. */
export interface AgentSender {
  /** Sender's address (`main` or a session address). */
  address: string;
  /** Sender's category label (`main`, `scheduled`, `external`, `spawned`, `artifact`). */
  category: string;
}

// ── Agent sessions ───────────────────────────────────────────────────

/** `GET /api/sessions/runs/{run_id}/transcript` response. */
export interface SessionTranscriptResponse {
  session: SessionSummary;
  messages: RecentMessage[];
}

// ── Chat history segments (paginated lazy-load) ──────────────────────

export interface RecentHistorySegment {
  kind: "recent";
  messages: RecentMessage[];
  next_cursor: string | null;
}

export interface EpisodeHistorySegment {
  kind: "episode";
  episode_id: string;
  date: string; // YYYY-MM-DD
  messages: RecentMessage[];
  next_cursor: string | null;
}

export type ChatHistorySegment = RecentHistorySegment | EpisodeHistorySegment;

// ── Status API ───────────────────────────────────────────────────────

export interface StatusResponse {
  mode: "setup" | "running";
  /** This build's version, the same string the workbench SDK exposes as `residuum.version`. */
  version: string;
  /** Feature ids this build supports, the same list the workbench SDK exposes as `residuum.features`. */
  features: string[];
  /** Each checkpoint repository's on-disk size and count, or `null` if just-now unreadable. */
  checkpoints: { workspace: RepoStats | null; config: RepoStats | null };
}

// ── Setup wizard types ──────────────────────────────────────────────

export type ProviderKey = "anthropic" | "openai" | "gemini" | "fireworks" | "ollama";

export interface ProviderConfig {
  apiKey: string;
  model: string;
  url: string;
}

export interface RoleConfig {
  provider: string;
  url: string;
  model: string;
}

export interface EmbeddingConfig {
  provider: string;
  model: string;
}

export interface BackgroundModelConfig {
  provider: string;
  model: string;
}

export interface McpServerEntry {
  name: string;
  /** Defaults to `"stdio"` when absent (e.g. entries from the setup wizard). */
  transport?: "stdio" | "http";
  /** stdio only: the executable to spawn. */
  command: string;
  /** stdio only. */
  args: string[];
  /** stdio only. */
  env: Record<string, string>;
  /** http only: the server's URL. */
  url?: string;
  /** http only. */
  headers?: Record<string, string>;
}

export interface McpRequiredInput {
  field: string;
  label: string;
}

export interface McpCatalogEntry {
  name: string;
  description: string;
  command: string;
  args: string[];
  env: Record<string, string>;
  category: string;
  requires_input: McpRequiredInput[];
  install_hint: string;
}

export interface IntegrationsConfig {
  discordToken: string;
  telegramToken: string;
  teamsAppId: string;
  teamsTenantId: string;
  teamsAppPassword: string;
}

export interface SetupWizardState {
  userName: string;
  timezone: string;
  selectedProviders: ProviderKey[];
  providerConfigs: Record<ProviderKey, ProviderConfig>;
  mainProvider: ProviderKey;
  roles: Record<string, RoleConfig>;
  embeddingModel: EmbeddingConfig;
  backgroundModels: Record<string, BackgroundModelConfig>;
  mcpServers: McpServerEntry[];
  integrations: IntegrationsConfig;
  secretRefs: Record<string, string>;
}

// ── Setup API response types ────────────────────────────────────────

export interface TimezoneResponse {
  timezone: string;
}

export interface ModelsResponse {
  models: { id: string; name: string }[];
  error?: string;
}

export interface SecretResponse {
  reference: string;
}

/** How serious a diagnostic is: `error` means the affected file, entry, or
 * pulse won't load or run until fixed; `warning` means it still works but is
 * worth a second look (a deprecated field, say). */
export type DiagnosticSeverity = "error" | "warning";

/** Where in the file a diagnostic applies. A parser that reports a position
 * gives `line` or `line_column`; a problem found only after parsing (no
 * source position to point at) gives `path`, a key path like
 * `mcpServers.filesystem` or `pulses.morning-check`. */
export type DiagnosticLocation =
  | { kind: "line"; line: number }
  | { kind: "line_column"; line: number; column: number }
  | { kind: "path"; path: string };

/** One problem found in a strictly-parsed file (config.toml, providers.toml,
 * config/channels.toml, config/mcp.json, config/a2a.json, HEARTBEAT.yml, a
 * skill's SKILL.md frontmatter) — see `POST /api/workspace/validate` and the
 * `diagnostics` field on write/move/save responses. */
export interface Diagnostic {
  severity: DiagnosticSeverity;
  message: string;
  location?: DiagnosticLocation;
}

export interface ValidateResponse {
  valid: boolean;
  error?: string;
  diagnostics?: Diagnostic[];
  /** On a successful Settings PATCH: the checkpoint taken just before the
   * write. Absent when that checkpoint failed (the write still happened). */
  checkpoint_id?: string;
}

// ── Settings types ───────────────────────────────────────────────────

export type SettingsSection =
  | "runtime"
  | "providers"
  | "memory"
  | "integrations"
  | "mcp"
  | "agent-keys"
  | "a2a"
  | "history";

export type SettingsMode = "simple" | "advanced" | "raw";

export interface RollbackNoticeResponse {
  attempted_version: string;
  reason: string;
  at: string;
}

export interface UpdateStatusResponse {
  current: string;
  latest: string | null;
  update_available: boolean;
  last_checked: string | null;
  checking: boolean;
  /** Present when the most recent restart rolled back instead of completing. */
  rollback_notice: RollbackNoticeResponse | null;
}

export type CloudTunnelStatus = "disconnected" | "connecting" | "connected";

export interface CloudStatusResponse {
  status: CloudTunnelStatus;
  user_id: string | null;
  has_token: boolean;
  enabled: boolean;
  /** True when this response was served to a browser viewing the gateway through the tunnel. */
  viewed_via_tunnel: boolean;
}

export interface SettingsProviderEntry {
  name: string;
  type: string;
  apiKey: string;
  url: string;
  keepAlive: string;
}

export interface RoleOverrides {
  temperature: string;
  thinking: string;
}

export type ModelRoleKey =
  | "main"
  | "default"
  | "observer"
  | "reflector"
  | "pulse"
  | "subconscious"
  | "embedding"
  | "bgSmall"
  | "bgMedium"
  | "bgLarge";

export interface SettingsModelAssignments {
  main: string;
  default: string;
  observer: string;
  reflector: string;
  pulse: string;
  subconscious: string;
  embedding: string;
  bgSmall: string;
  bgMedium: string;
  bgLarge: string;
  overrides: Record<string, RoleOverrides>;
}

/** One agent key as the API describes it. Values are never sent. */
export interface AgentKeyInfo {
  name: string;
  env_var: string;
  description: string;
  created_by: "user" | "agent";
}

export interface AgentKeysListResponse {
  keys: AgentKeyInfo[];
}

export interface SetAgentKeyResponse {
  name: string;
  env_var: string;
}

export interface SecretsListResponse {
  names: string[];
}

export interface DeleteSecretResponse {
  deleted: boolean;
}

// ── A2A types ────────────────────────────────────────────────────────

/** How this agent is reachable over A2A, and any live problem with it. */
export interface A2aStatusResponse {
  enabled: boolean;
  port: number;
  visibility: "public" | "private";
  /** This agent's own tunnel/reverse proxy origin, or null when none is set. */
  public_url: string | null;
  /** Whether something is currently answering on the A2A port. */
  listener_running: boolean;
  /** Plain-language problem with the workspace agent card, or null if it's fine. */
  card_error: string | null;
}

/** One caller key other agents can present to reach this one. Never carries the token. */
export interface A2aKeyInfo {
  name: string;
  description: string;
  created_at: string;
}

export interface A2aKeysListResponse {
  keys: A2aKeyInfo[];
}

/** Response from creating a caller key — the token is shown only here, once. */
export interface CreateA2aKeyResponse {
  name: string;
  token: string;
}

/** One skill this agent (or a remote agent's card) advertises. */
export interface A2aCardSkill {
  id: string;
  name: string;
  description?: string;
}

/** The fields of the served Agent Card this settings page shows a preview of. */
export interface A2aAgentCard {
  name: string;
  description: string;
  skills: A2aCardSkill[];
}

export type A2aAgentStatus = "pending" | "ok" | "error";

/** A remote agent listed in `config/a2a.json`, or discovered as a sibling instance. */
export interface A2aRemoteAgent {
  name: string;
  url: string;
  source: "config" | "sibling";
  status: A2aAgentStatus;
  error: string | null;
  card: A2aAgentCard | null;
}

// ── Workspace types ─────────────────────────────────────────────────

export interface WorkspaceEntry {
  name: string;
  entry_type: "file" | "directory";
  size: number | null;
  modified: number;
  version: string;
}

/** Response from `PUT /api/workspace/file` and `PUT /api/workspace/raw`.
 * `saved` is always `true` — an invalid strictly-parsed file (HEARTBEAT.yml,
 * say) is still written; `diagnostics` names what's wrong with it instead of
 * the save being rejected. */
export interface WorkspaceWriteResponse {
  saved: boolean;
  version: string;
  diagnostics?: Diagnostic[];
}

/** Response from `POST /api/workspace/move`. */
export interface WorkspaceMoveResponse {
  moved: boolean;
  version: string | null;
  diagnostics?: Diagnostic[];
}

/** Response from `POST /api/workspace/validate`. */
export interface WorkspaceValidateResponse {
  diagnostics: Diagnostic[];
}

// ── Feed items (UI rendering) ────────────────────────────────────────

export type ConnectionStatus = "connecting" | "connected" | "disconnected";

export interface ToolCallState {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  status: "running" | "done" | "error";
  result?: string;
}

interface FeedItemBase {
  id: number;
}

/**
 * The turn a user message started, once it's finished — set from a live
 * `turn_ended`/`session_turn_ended` frame, never from history (checkpoints
 * don't persist a turn's id past the live session that ran it, so "Undo
 * this turn" is only offered for a turn observed live). `changed` is
 * `null` until checked against the workspace's checkpoint history for this
 * turn id, then `true`/`false`.
 */
export interface TurnRef {
  turnId: string;
  changed: boolean | null;
}

export interface UserFeedItem extends FeedItemBase {
  kind: "user";
  content: string;
  images?: ImageAttachment[];
  sender?: MessageSender;
  turn?: TurnRef;
}

export interface AssistantFeedItem extends FeedItemBase {
  kind: "assistant";
  content: string;
}

export interface DividerFeedItem extends FeedItemBase {
  kind: "divider";
  label: string;
  variant?: "episode" | "day";
}

export interface CompressedMarkerFeedItem extends FeedItemBase {
  kind: "compressed-marker";
}

export interface ToolGroupFeedItem extends FeedItemBase {
  kind: "tool-group";
  calls: ToolCallState[];
}

export interface FileAttachmentFeedItem extends FeedItemBase {
  kind: "file-attachment";
  filename: string;
  mimeType: string;
  size: number;
  url: string;
  caption: string | null;
}

/**
 * Client-originated, ephemeral system text rendered inline in the chat
 * stream. Used for slash command output (`/help`, `/status`, `/context`)
 * that the user wants to read carefully but should not persist across
 * reloads or land in conversation history.
 */
export interface LocalSystemFeedItem extends FeedItemBase {
  kind: "local-system";
  content: string;
}

/**
 * A message one agent sent another: a session's result relayed to the main
 * agent (or any `message_agent` call to it), or, inside a session's
 * transcript, a message from another agent. Rendered as a compact item that
 * links to the sending session.
 */
export interface AgentMessageFeedItem extends FeedItemBase {
  kind: "agent-message";
  /** Sender's address (`main` or a session address). */
  from: string;
  /** Sender's category label, when known. */
  category: string | null;
  content: string;
  /** Sending run, when known (live frames carry it; history doesn't). */
  runId: string | null;
}

/**
 * A one-line status note inside a session view: delivery outcomes, command
 * failures, session errors, and the run finishing.
 */
export interface StatusFeedItem extends FeedItemBase {
  kind: "status";
  tone: "info" | "error";
  content: string;
  /** Full technical detail behind an expandable toggle, when there is one. */
  details?: string;
}

export type FeedItem =
  | AgentMessageFeedItem
  | StatusFeedItem
  | UserFeedItem
  | AssistantFeedItem
  | DividerFeedItem
  | CompressedMarkerFeedItem
  | ToolGroupFeedItem
  | FileAttachmentFeedItem
  | LocalSystemFeedItem;

// ── User Inbox ───────────────────────────────────────────────────────

// Field names match the JSON wire format as-is (snake_case), consistent with
// the rest of UserInboxItem below — this endpoint doesn't go through the
// camelCase mapping step that ServerMessage-derived feed items do.
export interface UserInboxAttachment {
  filename: string;
  mime_type: string;
  size: number;
  url: string;
}

export interface UserInboxItem {
  id: string;
  title: string;
  body: string;
  source: string;
  timestamp: string;
  read: boolean;
  attachments: UserInboxAttachment[];
}
