// ── Protocol types (generated by ts-rs from Rust source) ─────────────

import type {
  ImageAttachment as _ImageAttachment,
  SessionSummary as _SessionSummary,
} from "./generated/protocol";
export type {
  ClientMessage,
  ServerMessage,
  ImageAttachment,
  SessionCategory,
  SessionCommandErrorCode,
  SessionDeliveryOutcome,
  SessionListResponse,
  SessionRunStatus,
  SessionState,
  SessionSummary,
  WorkbenchInfo,
  WorkbenchRelayOrigins,
  ArtifactSummary,
} from "./generated/protocol";

// Local aliases for use within this file
type ImageAttachment = _ImageAttachment;
type SessionSummary = _SessionSummary;

// ── Chat history ─────────────────────────────────────────────────────

export interface ToolCallRecord {
  id: string;
  name: string;
  /**
   * Deliberately `unknown`: the wire shape depends on the source. History
   * (`/api/chat/history`) serializes this from a Rust `serde_json::Value`, so
   * it arrives as an **object**; other paths have carried it as a JSON
   * **string**. Typing it as `string` previously invited a bare
   * `JSON.parse(...)`, which throws `SyntaxError` on an object and took out
   * the whole feed render.
   *
   * Keep this `unknown` so the compiler forces every reader through
   * `normalizeToolArgs()` instead of assuming a shape.
   */
  arguments: unknown;
}

/** Person behind a user message that arrived on a chat interface. */
export interface MessageSender {
  name: string;
  id: string;
  interface: string;
  location?: string;
}

export interface RecentMessage {
  role: "user" | "assistant" | "tool" | "system";
  content: string;
  tool_calls?: ToolCallRecord[];
  tool_call_id?: string;
  timestamp: string;
  visibility: "user" | "background";
  sender?: MessageSender;
  /** The agent that sent this message, for one agent's message to another. */
  agent_sender?: AgentSender;
}

/** The agent behind a message one agent sent another. */
export interface AgentSender {
  /** Sender's address (`main` or a session address). */
  address: string;
  /** Sender's category label (`main`, `scheduled`, `external`, `spawned`). */
  category: string;
}

// ── Agent sessions ───────────────────────────────────────────────────

/** `GET /api/sessions/runs/{run_id}/transcript` response. */
export interface SessionTranscriptResponse {
  session: SessionSummary;
  messages: RecentMessage[];
}

// ── Chat history segments (paginated lazy-load) ──────────────────────

export interface RecentHistorySegment {
  kind: "recent";
  messages: RecentMessage[];
  next_cursor: string | null;
}

export interface EpisodeHistorySegment {
  kind: "episode";
  episode_id: string;
  date: string; // YYYY-MM-DD
  messages: RecentMessage[];
  next_cursor: string | null;
}

export type ChatHistorySegment = RecentHistorySegment | EpisodeHistorySegment;

// ── Status API ───────────────────────────────────────────────────────

export interface StatusResponse {
  mode: "setup" | "running";
}

// ── Setup wizard types ──────────────────────────────────────────────

export type ProviderKey = "anthropic" | "openai" | "gemini" | "fireworks" | "ollama";

export interface ProviderConfig {
  apiKey: string;
  model: string;
  url: string;
}

export interface RoleConfig {
  provider: string;
  url: string;
  model: string;
}

export interface EmbeddingConfig {
  provider: string;
  model: string;
}

export interface BackgroundModelConfig {
  provider: string;
  model: string;
}

export interface McpServerEntry {
  name: string;
  command: string;
  args: string[];
  env: Record<string, string>;
}

export interface McpRequiredInput {
  field: string;
  label: string;
}

export interface McpCatalogEntry {
  name: string;
  description: string;
  command: string;
  args: string[];
  env: Record<string, string>;
  category: string;
  requires_input: McpRequiredInput[];
  install_hint: string;
}

export interface IntegrationsConfig {
  discordToken: string;
  telegramToken: string;
  teamsAppId: string;
  teamsTenantId: string;
  teamsAppPassword: string;
}

export interface SetupWizardState {
  userName: string;
  timezone: string;
  selectedProviders: ProviderKey[];
  providerConfigs: Record<ProviderKey, ProviderConfig>;
  mainProvider: ProviderKey;
  roles: Record<string, RoleConfig>;
  embeddingModel: EmbeddingConfig;
  backgroundModels: Record<string, BackgroundModelConfig>;
  mcpServers: McpServerEntry[];
  integrations: IntegrationsConfig;
  secretRefs: Record<string, string>;
}

// ── Setup API response types ────────────────────────────────────────

export interface TimezoneResponse {
  timezone: string;
}

export interface ModelsResponse {
  models: { id: string; name: string }[];
  error?: string;
}

export interface SecretResponse {
  reference: string;
}

export interface ValidateResponse {
  valid: boolean;
  error?: string;
}

// ── Settings types ───────────────────────────────────────────────────

export type SettingsSection =
  | "runtime"
  | "providers"
  | "memory"
  | "integrations"
  | "mcp"
  | "agent-keys";

export type SettingsMode = "simple" | "advanced" | "raw";

export interface UpdateStatusResponse {
  current: string;
  latest: string | null;
  update_available: boolean;
  last_checked: string | null;
  checking: boolean;
}

export type CloudTunnelStatus = "disconnected" | "connecting" | "connected";

export interface CloudStatusResponse {
  status: CloudTunnelStatus;
  user_id: string | null;
  has_token: boolean;
  enabled: boolean;
}

export interface SettingsProviderEntry {
  name: string;
  type: string;
  apiKey: string;
  url: string;
  keepAlive: string;
}

export interface RoleOverrides {
  temperature: string;
  thinking: string;
}

export type ModelRoleKey =
  | "main"
  | "default"
  | "observer"
  | "reflector"
  | "pulse"
  | "subconscious"
  | "embedding"
  | "bgSmall"
  | "bgMedium"
  | "bgLarge";

export interface SettingsModelAssignments {
  main: string;
  default: string;
  observer: string;
  reflector: string;
  pulse: string;
  subconscious: string;
  embedding: string;
  bgSmall: string;
  bgMedium: string;
  bgLarge: string;
  overrides: Record<string, RoleOverrides>;
}

/** One agent key as the API describes it. Values are never sent. */
export interface AgentKeyInfo {
  name: string;
  env_var: string;
  description: string;
  created_by: "user" | "agent";
}

export interface AgentKeysListResponse {
  keys: AgentKeyInfo[];
}

export interface SetAgentKeyResponse {
  name: string;
  env_var: string;
}

export interface SecretsListResponse {
  names: string[];
}

export interface DeleteSecretResponse {
  deleted: boolean;
}

// ── Workspace types ─────────────────────────────────────────────────

export interface WorkspaceEntry {
  name: string;
  entry_type: "file" | "directory";
  size: number | null;
}

// ── Feed items (UI rendering) ────────────────────────────────────────

export type ConnectionStatus = "connecting" | "connected" | "disconnected";

export interface ToolCallState {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  status: "running" | "done" | "error";
  result?: string;
}

interface FeedItemBase {
  id: number;
}

export interface UserFeedItem extends FeedItemBase {
  kind: "user";
  content: string;
  images?: ImageAttachment[];
  sender?: MessageSender;
}

export interface AssistantFeedItem extends FeedItemBase {
  kind: "assistant";
  content: string;
}

export interface DividerFeedItem extends FeedItemBase {
  kind: "divider";
  label: string;
  variant?: "episode" | "day";
}

export interface CompressedMarkerFeedItem extends FeedItemBase {
  kind: "compressed-marker";
}

export interface ToolGroupFeedItem extends FeedItemBase {
  kind: "tool-group";
  calls: ToolCallState[];
}

export interface FileAttachmentFeedItem extends FeedItemBase {
  kind: "file-attachment";
  filename: string;
  mimeType: string;
  size: number;
  url: string;
  caption: string | null;
}

/**
 * Client-originated, ephemeral system text rendered inline in the chat
 * stream. Used for slash command output (`/help`, `/status`, `/context`)
 * that the user wants to read carefully but should not persist across
 * reloads or land in conversation history.
 */
export interface LocalSystemFeedItem extends FeedItemBase {
  kind: "local-system";
  content: string;
}

/**
 * A message one agent sent another: a session's result relayed to the main
 * agent (or any `message_agent` call to it), or, inside a session's
 * transcript, a message from another agent. Rendered as a compact item that
 * links to the sending session.
 */
export interface AgentMessageFeedItem extends FeedItemBase {
  kind: "agent-message";
  /** Sender's address (`main` or a session address). */
  from: string;
  /** Sender's category label, when known. */
  category: string | null;
  content: string;
  /** Sending run, when known (live frames carry it; history doesn't). */
  runId: string | null;
}

/**
 * A one-line status note inside a session view: delivery outcomes, command
 * failures, session errors, and the run finishing.
 */
export interface StatusFeedItem extends FeedItemBase {
  kind: "status";
  tone: "info" | "error";
  content: string;
}

export type FeedItem =
  | AgentMessageFeedItem
  | StatusFeedItem
  | UserFeedItem
  | AssistantFeedItem
  | DividerFeedItem
  | CompressedMarkerFeedItem
  | ToolGroupFeedItem
  | FileAttachmentFeedItem
  | LocalSystemFeedItem;

// ── User Inbox ───────────────────────────────────────────────────────

// Field names match the JSON wire format as-is (snake_case), consistent with
// the rest of UserInboxItem below — this endpoint doesn't go through the
// camelCase mapping step that ServerMessage-derived feed items do.
export interface UserInboxAttachment {
  filename: string;
  mime_type: string;
  size: number;
  url: string;
}

export interface UserInboxItem {
  id: string;
  title: string;
  body: string;
  source: string;
  timestamp: string;
  read: boolean;
  attachments: UserInboxAttachment[];
}
