// ── Protocol types (generated by ts-rs from Rust source) ─────────────

import type { ImageAttachment as _ImageAttachment } from "./generated/protocol";
export type { ClientMessage, ServerMessage, ImageAttachment } from "./generated/protocol";

// Local alias for use within this file
type ImageAttachment = _ImageAttachment;

// ── Chat history ─────────────────────────────────────────────────────

export interface ToolCallRecord {
  id: string;
  name: string;
  arguments: string;
}

export interface RecentMessage {
  role: "user" | "assistant" | "tool" | "system";
  content: string;
  tool_calls?: ToolCallRecord[];
  tool_call_id?: string;
  timestamp: string;
  project_context: string;
  visibility: "user" | "background";
}

// ── Chat history segments (paginated lazy-load) ──────────────────────

export interface RecentHistorySegment {
  kind: "recent";
  messages: RecentMessage[];
  next_cursor: string | null;
}

export interface EpisodeHistorySegment {
  kind: "episode";
  episode_id: string;
  date: string; // YYYY-MM-DD
  context: string;
  messages: RecentMessage[];
  next_cursor: string | null;
}

export type ChatHistorySegment = RecentHistorySegment | EpisodeHistorySegment;

// ── Status API ───────────────────────────────────────────────────────

export interface StatusResponse {
  mode: "setup" | "running";
}

// ── Setup wizard types ──────────────────────────────────────────────

export type ProviderKey = "anthropic" | "openai" | "gemini" | "ollama";

export interface ProviderConfig {
  apiKey: string;
  model: string;
  url: string;
}

export interface RoleConfig {
  provider: string;
  url: string;
  model: string;
}

export interface EmbeddingConfig {
  provider: string;
  model: string;
}

export interface BackgroundModelConfig {
  provider: string;
  model: string;
}

export interface McpServerEntry {
  name: string;
  command: string;
  args: string[];
  env: Record<string, string>;
}

export interface McpRequiredInput {
  field: string;
  label: string;
}

export interface McpCatalogEntry {
  name: string;
  description: string;
  command: string;
  args: string[];
  env: Record<string, string>;
  category: string;
  requires_input: McpRequiredInput[];
  install_hint: string;
}

export interface IntegrationsConfig {
  discordToken: string;
  telegramToken: string;
}

export interface SetupWizardState {
  userName: string;
  timezone: string;
  selectedProviders: ProviderKey[];
  providerConfigs: Record<ProviderKey, ProviderConfig>;
  mainProvider: ProviderKey;
  roles: Record<string, RoleConfig>;
  embeddingModel: EmbeddingConfig;
  backgroundModels: Record<string, BackgroundModelConfig>;
  mcpServers: McpServerEntry[];
  integrations: IntegrationsConfig;
  secretRefs: Record<string, string>;
}

// ── Setup API response types ────────────────────────────────────────

export interface TimezoneResponse {
  timezone: string;
}

export interface ModelsResponse {
  models: { id: string; name: string }[];
  error?: string;
}

export interface SecretResponse {
  reference: string;
}

export interface ValidateResponse {
  valid: boolean;
  error?: string;
}

// ── Settings types ───────────────────────────────────────────────────

export type SettingsSection = "runtime" | "providers" | "memory" | "integrations" | "mcp";

export type SettingsMode = "simple" | "advanced" | "raw";

export interface UpdateStatusResponse {
  current: string;
  latest: string | null;
  update_available: boolean;
  last_checked: string | null;
  checking: boolean;
}

export type CloudTunnelStatus = "disconnected" | "connecting" | "connected";

export interface CloudStatusResponse {
  status: CloudTunnelStatus;
  user_id: string | null;
  has_token: boolean;
  enabled: boolean;
}

export interface SettingsProviderEntry {
  name: string;
  type: string;
  apiKey: string;
  url: string;
  keepAlive: string;
}

export interface RoleOverrides {
  temperature: string;
  thinking: string;
}

export type ModelRoleKey =
  | "main"
  | "default"
  | "observer"
  | "reflector"
  | "pulse"
  | "embedding"
  | "bgSmall"
  | "bgMedium"
  | "bgLarge";

export interface SettingsModelAssignments {
  main: string;
  default: string;
  observer: string;
  reflector: string;
  pulse: string;
  embedding: string;
  bgSmall: string;
  bgMedium: string;
  bgLarge: string;
  overrides: Record<string, RoleOverrides>;
}

export interface SecretsListResponse {
  names: string[];
}

export interface DeleteSecretResponse {
  deleted: boolean;
}

// ── Workspace types ─────────────────────────────────────────────────

export interface WorkspaceEntry {
  name: string;
  entry_type: "file" | "directory";
  size: number | null;
}

// ── Feed items (UI rendering) ────────────────────────────────────────

export type ConnectionStatus = "connecting" | "connected" | "disconnected";

export interface ToolCallState {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  status: "running" | "done" | "error";
  result?: string;
}

interface FeedItemBase {
  id: number;
}

export interface UserFeedItem extends FeedItemBase {
  kind: "user";
  content: string;
  images?: ImageAttachment[];
}

export interface AssistantFeedItem extends FeedItemBase {
  kind: "assistant";
  content: string;
}

export interface DividerFeedItem extends FeedItemBase {
  kind: "divider";
  label: string;
  variant?: "episode" | "day";
}

export interface CompressedMarkerFeedItem extends FeedItemBase {
  kind: "compressed-marker";
}

export interface ToolGroupFeedItem extends FeedItemBase {
  kind: "tool-group";
  calls: ToolCallState[];
}

export interface FileAttachmentFeedItem extends FeedItemBase {
  kind: "file-attachment";
  filename: string;
  mimeType: string;
  size: number;
  url: string;
  caption: string | null;
}

/**
 * Client-originated, ephemeral system text rendered inline in the chat
 * stream. Used for slash command output (`/help`, `/status`, `/context`)
 * that the user wants to read carefully but should not persist across
 * reloads or land in conversation history.
 */
export interface LocalSystemFeedItem extends FeedItemBase {
  kind: "local-system";
  content: string;
}

export type FeedItem =
  | UserFeedItem
  | AssistantFeedItem
  | DividerFeedItem
  | CompressedMarkerFeedItem
  | ToolGroupFeedItem
  | FileAttachmentFeedItem
  | LocalSystemFeedItem;

// ── User Inbox ───────────────────────────────────────────────────────

export interface UserInboxItem {
  id: string;
  title: string;
  body: string;
  source: string;
  timestamp: string;
  read: boolean;
  attachments: string[];
}
