//! Session runtime: executes a session's turns with bounded concurrency and
//! drives its lifecycle from fork through completion.
//!
//! `SessionRuntime::spawn` is the sole entry point that starts a new run. It
//! registers the run in the [`SessionRegistry`], runs one turn through the
//! shared turn executor, then lingers the session in `idle` until its
//! category's timeout elapses or it is stopped, before finalizing the run in
//! the [`SessionStore`] and publishing its result on the bus.

use std::sync::Arc;
use std::time::Duration;

use chrono::Utc;
use futures_util::FutureExt;
use tokio::sync::{Semaphore, mpsc};
use tokio_util::sync::CancellationToken;

use crate::agent::interrupt::Interrupt;
use crate::agent::recent_messages::RecentMessages;
use crate::bus::{
    AgentMessageEvent, AgentResultEvent, AgentResultStatus, EventTrigger, HEARTBEAT_OK,
    HEARTBEAT_URGENT, Publisher, ResultDisposition, SessionAddress, SkillName, topics,
};
use crate::config::BackgroundConfig;

use super::messaging::AgentMessenger;
use super::registry::{
    MAIN_ADDRESS, ResumePoint, SessionCategory, SessionInfo, SessionRegistry, SessionState,
    generate_run_id,
};
use super::session_memory::{SessionMemory, SessionMemoryEnv, complete_session_memory};
use super::store::{RunTranscriptSink, SessionStore};
use super::subagent::{SubAgentResources, TurnKickoff, execute_subagent};
use super::types::{SubAgentConfig, truncate_prompt_preview};

/// Idle timeouts per category, resolved once from config at construction.
///
/// Like `max_concurrent`, these are fixed for the lifetime of the runtime —
/// a config reload updates `SpawnContext.background_config` for tier
/// resolution but does not resize this runtime, the same limitation
/// `max_concurrent` already has today.
#[derive(Debug, Clone, Copy)]
pub(crate) struct IdleTimeouts {
    scheduled: Duration,
    spawned: Duration,
    external: Duration,
}

impl IdleTimeouts {
    /// Resolve the idle timeout for a session, given its trigger.
    ///
    /// Webhook sessions are `external` but use the `scheduled` timeout: a
    /// webhook call is one-shot with no expected back-and-forth.
    fn for_trigger(&self, trigger: &EventTrigger) -> Duration {
        match SessionCategory::from_trigger(trigger) {
            SessionCategory::Scheduled => self.scheduled,
            SessionCategory::Spawned => self.spawned,
            SessionCategory::External => {
                if matches!(trigger, EventTrigger::Webhook(_)) {
                    self.scheduled
                } else {
                    self.external
                }
            }
        }
    }
}

impl From<&BackgroundConfig> for IdleTimeouts {
    fn from(cfg: &BackgroundConfig) -> Self {
        Self {
            scheduled: cfg.idle_timeout_scheduled,
            spawned: cfg.idle_timeout_spawned,
            external: cfg.idle_timeout_external,
        }
    }
}

/// A request to fork a new session run.
pub(crate) struct SessionSpawnRequest {
    /// Address the session runs under (pre-generated by the caller).
    pub address: SessionAddress,
    /// Human-readable source label (e.g. `"pulse:email_check"`).
    pub source_label: String,
    /// What triggered this session.
    pub trigger: EventTrigger,
    /// Skill the session runs with, if any.
    pub agent_skill: Option<SkillName>,
    /// The session's turn configuration.
    pub subagent_config: SubAgentConfig,
}

/// Executes session turns with bounded concurrency, tracking each session's
/// lifecycle in the registry and its record in the store.
pub struct SessionRuntime {
    semaphore: Arc<Semaphore>,
    registry: Arc<SessionRegistry>,
    store: Arc<SessionStore>,
    idle_timeouts: IdleTimeouts,
    publisher: Publisher,
    tz: chrono_tz::Tz,
    /// Used only to resume a run whose interrupt channel still held agent
    /// messages at the moment its own teardown drained it — see
    /// `finish_run`. Ordinary live delivery goes through the registry
    /// directly and never touches this.
    messenger: Arc<AgentMessenger>,
}

/// Shared handles a session run needs for the lifetime of its driver task,
/// grouped to keep [`run_session`]'s signature small.
struct RunEnv {
    semaphore: Arc<Semaphore>,
    registry: Arc<SessionRegistry>,
    store: Arc<SessionStore>,
    publisher: Publisher,
    tz: chrono_tz::Tz,
    messenger: Arc<AgentMessenger>,
}

impl SessionRuntime {
    /// Create a new runtime with the given concurrency limit.
    #[must_use]
    pub(crate) fn new(
        registry: Arc<SessionRegistry>,
        store: Arc<SessionStore>,
        max_concurrent: usize,
        idle_timeouts: impl Into<IdleTimeouts>,
        publisher: Publisher,
        tz: chrono_tz::Tz,
        messenger: Arc<AgentMessenger>,
    ) -> Self {
        Self {
            semaphore: Arc::new(Semaphore::new(max_concurrent)),
            registry,
            store,
            idle_timeouts: idle_timeouts.into(),
            publisher,
            tz,
            messenger,
        }
    }

    /// Fork and run a new session.
    ///
    /// Registers the session as `forking` immediately (so it is discoverable
    /// even before a concurrency permit is available), then drives it through
    /// `running` → `idle` → `completing` → `completed` on a detached task.
    #[tracing::instrument(skip_all, fields(session.address = %req.address))]
    pub(crate) fn spawn(&self, req: SessionSpawnRequest, resources: Option<SubAgentResources>) {
        let run_id = generate_run_id();
        let category = SessionCategory::from_trigger(&req.trigger);
        let spawner = matches!(category, SessionCategory::Spawned)
            .then(|| SessionAddress::from(MAIN_ADDRESS));
        let purpose = truncate_prompt_preview(&req.subagent_config.prompt);
        let idle_timeout = self.idle_timeouts.for_trigger(&req.trigger);
        let model_tier = req.subagent_config.model_tier;

        let info = SessionInfo {
            address: req.address,
            run_id,
            category,
            trigger: req.trigger,
            source_label: req.source_label,
            state: SessionState::Forking,
            spawner,
            depth: super::registry::MAIN_DEPTH + 1,
            purpose,
            agent_skill: req.agent_skill,
            model_tier,
            started_at: Utc::now(),
        };

        let stop_token = CancellationToken::new();
        let interrupt_rx = self.registry.register(info.clone(), stop_token.clone());
        tracing::info!(address = %info.address, source_label = %info.source_label, "session forking");

        let env = RunEnv {
            semaphore: Arc::clone(&self.semaphore),
            registry: Arc::clone(&self.registry),
            store: Arc::clone(&self.store),
            publisher: self.publisher.clone(),
            tz: self.tz,
            messenger: Arc::clone(&self.messenger),
        };
        let config = req.subagent_config;

        tokio::spawn(async move {
            env.store.begin_run(&info).await;

            // Cloned up front so cleanup still has something to work with if
            // the task panics — the originals (including `resources`, which
            // is not `Clone`) are moved into `run_session` and gone with it
            // once the panic unwinds past this point.
            let panic_info = info.clone();
            let registry = Arc::clone(&env.registry);
            let store = Arc::clone(&env.store);
            let publisher = env.publisher.clone();
            let tz = env.tz;
            let mem_extras = resources.as_ref().map(|res| PanicMemoryExtras {
                observer: Arc::clone(&res.observer),
                merge_writer: Arc::clone(&res.merge_writer),
                layout: res.layout.clone(),
                episode_skip_token_floor: res.episode_skip_token_floor,
            });

            let outcome = std::panic::AssertUnwindSafe(run_session(
                info,
                config,
                resources,
                stop_token,
                interrupt_rx,
                idle_timeout,
                env,
            ))
            .catch_unwind()
            .await;

            if let Err(panic) = outcome {
                let msg = crate::util::panic_message(&*panic);
                tracing::error!(
                    address = %panic_info.address,
                    run_id = %panic_info.run_id,
                    panic = msg,
                    "session task panicked"
                );
                recover_from_panic(
                    &panic_info,
                    &registry,
                    &store,
                    &publisher,
                    tz,
                    msg,
                    mem_extras,
                )
                .await;
            }
        });
    }

    /// Stop every live session and wait for their runs to finish completing
    /// and being recorded, so a graceful shutdown doesn't leave sessions for
    /// startup recovery to pick up.
    ///
    /// Waits up to `timeout` by polling the registry; logs a warning and
    /// returns if sessions are still live once the deadline passes (their
    /// runs remain in the store as `running` and get swept by startup
    /// recovery on the next boot).
    pub(crate) async fn shutdown(&self, timeout: Duration) {
        let signalled = self.registry.stop_all();
        if signalled == 0 {
            return;
        }
        tracing::info!(sessions = signalled, "stopping live sessions for shutdown");

        let deadline = tokio::time::Instant::now() + timeout;
        while tokio::time::Instant::now() < deadline {
            if self.registry.list_live().is_empty() {
                tracing::info!("all sessions completed for shutdown");
                return;
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
        tracing::warn!(
            remaining = self.registry.list_live().len(),
            "shutdown timed out waiting for live sessions to complete"
        );
    }
}

/// Owned copies of the memory subsystem handles a run's completion pipeline
/// needs, cloned up front (before `resources` moves into [`run_session`])
/// since a panic unwinds through and drops the original `SubAgentResources`
/// — its provider/tools/MCP registry aren't `Clone`, but these three handles
/// are cheap `Arc`/owned clones and are all [`recover_from_panic`] needs to
/// run the same completion pipeline a normal run does.
struct PanicMemoryExtras {
    observer: Arc<crate::memory::observer::Observer>,
    merge_writer: Arc<crate::memory::merge_writer::MemoryMergeWriter>,
    layout: crate::workspace::layout::WorkspaceLayout,
    episode_skip_token_floor: usize,
}

/// Finalize a session's record and notify listeners after its task panicked,
/// mirroring the cleanup [`run_session`] performs on any other terminal path
/// — otherwise a panic would leave the session `running` forever in the
/// store and permanently registered as live.
///
/// Backfills the transcript from the run's durable `.transcript.jsonl`
/// sidecar (the same file [`RunTranscriptSink`] appended to during the run)
/// and, when the resources for it are available, runs the normal completion
/// memory pipeline over it — a panic mid-turn must not silently drop
/// whatever the run had already produced. The merge writer's own
/// idempotency check (see `crate::memory::merged_run_log`) makes this safe
/// even if the panic happened after a merge had already succeeded.
async fn recover_from_panic(
    info: &SessionInfo,
    registry: &SessionRegistry,
    store: &SessionStore,
    publisher: &Publisher,
    tz: chrono_tz::Tz,
    panic_msg: &str,
    mem_extras: Option<PanicMemoryExtras>,
) {
    registry.set_state(&info.address, SessionState::Completing);

    let transcript = store
        .read_incremental_transcript(&info.run_id, info.started_at)
        .await;

    let episode_id = if let Some(extras) = mem_extras {
        let summary = transcript
            .last()
            .map(|m| m.content.clone())
            .unwrap_or_default();
        let mem_env = SessionMemoryEnv {
            observer: extras.observer.as_ref(),
            merge_writer: extras.merge_writer.as_ref(),
            layout: &extras.layout,
            episode_skip_token_floor: extras.episode_skip_token_floor,
            tz,
        };
        let tag = crate::memory::types::SourceTag::session(
            info.address.to_string(),
            info.run_id.clone(),
            info.category.as_str(),
        );
        complete_session_memory(tag, &summary, &transcript, SessionMemory::new(), &mem_env).await
    } else {
        None
    };

    registry.record_resume_point(&info.address, resume_point(info, episode_id.clone()));

    let transcript_path = store
        .complete_run(
            info,
            SessionState::Completed.as_str(),
            transcript,
            episode_id,
        )
        .await;

    let status = AgentResultStatus::Failed {
        error: format!("session task panicked: {panic_msg}"),
    };
    let event = build_result_event(info, status, String::new(), transcript_path, tz);
    if let Err(e) = publisher.publish(topics::Background, event).await {
        tracing::warn!(error = %e, "failed to publish panicked session result to bus");
    }

    registry.remove(&info.address, &info.run_id);
    tracing::info!("session removed from registry after panic recovery");
}

/// Build the resume point a completed run leaves behind, so a later
/// `message_agent` call to its address can fork it again with a pointer back
/// to what it produced.
fn resume_point(info: &SessionInfo, episode_id: Option<String>) -> ResumePoint {
    ResumePoint {
        previous_run_id: info.run_id.clone(),
        previous_episode_id: episode_id,
        trigger: info.trigger.clone(),
        source_label: info.source_label.clone(),
        agent_skill: info.agent_skill.clone(),
        model_tier: info.model_tier,
    }
}

/// What ended a session's idle wait.
enum IdleOutcome {
    /// Stopped via `stop_agent` while idle.
    Stopped,
    /// The idle timeout elapsed with no new input.
    TimedOut,
    /// An agent message arrived; it becomes the next turn's kickoff.
    Woken(AgentMessageEvent),
}

/// Wait for a session's idle period to end: a stop, the idle timeout, or an
/// agent message delivered through the run's own interrupt channel (the
/// same channel a running turn drains at its tool-call checkpoints — see
/// `crate::background::messaging`). An interrupt kind other than
/// `AgentMessage` is not expected while idle (nothing else is ever sent into
/// a session's channel) but is ignored defensively rather than treated as a
/// wake, so the idle wait keeps going.
async fn wait_idle(
    stop_token: &CancellationToken,
    idle_timeout: Duration,
    interrupt_rx: &mut mpsc::Receiver<Interrupt>,
) -> IdleOutcome {
    loop {
        tokio::select! {
            biased;
            () = stop_token.cancelled() => return IdleOutcome::Stopped,
            () = tokio::time::sleep(idle_timeout) => {
                // `biased` means this arm can win even when a message landed
                // in the channel in the same poll (it's checked ahead of the
                // `recv()` arm below) — a `try_recv` here catches that exact
                // race before treating the run as genuinely timed out and
                // letting its caller move on to completing, which would
                // otherwise leave the message stranded in a channel about to
                // be drained and dropped (see `finish_run`).
                return match interrupt_rx.try_recv() {
                    Ok(Interrupt::AgentMessage(msg)) => IdleOutcome::Woken(msg),
                    Ok(_) | Err(_) => IdleOutcome::TimedOut,
                };
            }
            received = interrupt_rx.recv() => {
                match received {
                    Some(Interrupt::AgentMessage(msg)) => return IdleOutcome::Woken(msg),
                    Some(_) => {}
                    None => return IdleOutcome::TimedOut,
                }
            }
        }
    }
}

/// Drive one session run from permit acquisition through completion.
///
/// A run is one or more turns: the first is always the fork's task prompt;
/// any later one is an agent message that arrived while the session was
/// idle, per the design's messaging rules. `recent_messages` accumulates
/// across every turn in the run, so a session woken from idle still has its
/// earlier context, and staging/the final merge see the whole run's
/// transcript regardless of how many turns produced it.
#[tracing::instrument(skip_all, fields(session.address = %info.address, run.id = %info.run_id))]
async fn run_session(
    mut info: SessionInfo,
    config: SubAgentConfig,
    resources: Option<SubAgentResources>,
    stop_token: CancellationToken,
    mut interrupt_rx: mpsc::Receiver<Interrupt>,
    idle_timeout: Duration,
    env: RunEnv,
) {
    let mut recent_messages = RecentMessages::new();
    let mut memory = SessionMemory::new();
    let mut kickoff = TurnKickoff::Initial {
        prompt: config.prompt,
        context: config.context,
    };
    // Assigned on the loop's first iteration, which always runs at least
    // once (the run's initial turn), so both are definitely initialized by
    // the time anything after the loop reads them.
    let mut status;
    let mut summary;

    loop {
        (status, summary) = tokio::select! {
            biased;
            () = stop_token.cancelled() => {
                tracing::info!("session stopped before its turn started");
                (AgentResultStatus::Cancelled, String::new())
            }
            permit = env.semaphore.acquire() => {
                match permit {
                    Ok(_permit) => {
                        env.registry.set_state(&info.address, SessionState::Running);
                        let ctx = TurnCtx {
                            info: &info,
                            resources: resources.as_ref(),
                            stop_token: &stop_token,
                            store: &env.store,
                        };
                        run_turn(&ctx, &mut recent_messages, kickoff, &mut interrupt_rx).await
                    }
                    Err(_closed) => {
                        tracing::warn!("concurrency semaphore closed before session could acquire a permit");
                        (
                            AgentResultStatus::Failed {
                                error: "gateway is shutting down".to_string(),
                            },
                            String::new(),
                        )
                    }
                }
            }
        };

        // Per-turn threshold check: mirrors the main agent's own rotation,
        // run after every turn (not just once) since a run can now span
        // several. Staged observations are held locally and merged alongside
        // the final observation on completion.
        if let Some(res) = resources.as_ref() {
            let mem_env = session_memory_env(res, env.tz);
            memory
                .maybe_stage(recent_messages.messages(), &mem_env)
                .await;
        }

        // A cancelled run — whether stopped before its turn started or
        // mid-turn — skips lingering idle and goes straight to completing,
        // per the design: stopping a session moves it straight to
        // `completing`.
        if matches!(status, AgentResultStatus::Cancelled) {
            tracing::info!("session stopped, skipping idle and completing directly");
            break;
        }

        env.registry.set_state(&info.address, SessionState::Idle);
        tracing::debug!(
            idle_secs = idle_timeout.as_secs(),
            "session idle, awaiting further input or timeout"
        );
        match wait_idle(&stop_token, idle_timeout, &mut interrupt_rx).await {
            IdleOutcome::Stopped => {
                tracing::info!("session stopped while idle");
                break;
            }
            IdleOutcome::TimedOut => {
                tracing::debug!("session idle timeout elapsed");
                break;
            }
            IdleOutcome::Woken(msg) => {
                tracing::info!(from = %msg.from, "session woken by an agent message, starting another turn");
                kickoff = TurnKickoff::AgentMessage(msg);
            }
        }
    }

    // The run is genuinely ending now (stopped, or timed out with the race
    // above finding nothing) and `interrupt_rx` is about to be dropped —
    // drain whatever is still queued in it so a message that landed in the
    // narrow window between the loop's last check and here isn't silently
    // lost. `finish_run` resumes the session as a new run to deliver these
    // once this run has fully left the registry.
    let leftover_messages = drain_pending_agent_messages(&mut interrupt_rx);

    finish_run(
        &mut info,
        resources.as_ref(),
        RunOutcome {
            status,
            summary,
            memory,
            recent_messages,
            leftover_messages,
        },
        &env,
    )
    .await;
}

/// Drain every agent message still queued in a run's interrupt channel,
/// discarding any other interrupt kind (nothing else is ever sent into a
/// session's channel — see `wait_idle`).
fn drain_pending_agent_messages(
    interrupt_rx: &mut mpsc::Receiver<Interrupt>,
) -> Vec<AgentMessageEvent> {
    let mut drained = Vec::new();
    while let Ok(interrupt) = interrupt_rx.try_recv() {
        if let Interrupt::AgentMessage(msg) = interrupt {
            drained.push(msg);
        }
    }
    drained
}

/// What a run's turn loop produced, once it has ended — everything
/// [`finish_run`] needs to close it out, grouped to keep that function's
/// argument count down.
struct RunOutcome {
    status: AgentResultStatus,
    summary: String,
    memory: SessionMemory,
    recent_messages: RecentMessages,
    /// Agent messages still queued in the run's interrupt channel when
    /// [`drain_pending_agent_messages`] drained it — must be routed to the
    /// resumed run rather than silently dropped.
    leftover_messages: Vec<AgentMessageEvent>,
}

/// Finalize a run once its turn loop has ended: merge whatever it staged
/// (and a final extraction) into global memory, record the run's resume
/// point, write its completed store record, publish its result, and — if
/// any agent messages were still queued when the run's interrupt channel was
/// drained (see [`drain_pending_agent_messages`]) — resume the session as a
/// new run to deliver them, once this run has fully left the registry.
///
/// Split out of [`run_session`] purely to keep that function's line count
/// down — this is still exclusively its own tail end, not a reusable step.
async fn finish_run(
    info: &mut SessionInfo,
    resources: Option<&SubAgentResources>,
    outcome: RunOutcome,
    env: &RunEnv,
) {
    let RunOutcome {
        status,
        summary,
        memory,
        recent_messages,
        leftover_messages,
    } = outcome;

    info.state = SessionState::Completing;
    env.registry
        .set_state(&info.address, SessionState::Completing);

    // Merge into global memory before recording the run as completed, so a
    // successful merge's episode id lands in the same record. A stopped run
    // merges like any other — stopping is not discarding.
    let episode_id = if let Some(res) = resources {
        let mem_env = session_memory_env(res, env.tz);
        let tag = crate::memory::types::SourceTag::session(
            info.address.to_string(),
            info.run_id.clone(),
            info.category.as_str(),
        );
        complete_session_memory(tag, &summary, recent_messages.messages(), memory, &mem_env).await
    } else {
        None
    };

    let point = resume_point(info, episode_id.clone());
    env.registry
        .record_resume_point(&info.address, point.clone());

    let transcript_path = env
        .store
        .complete_run(
            info,
            SessionState::Completed.as_str(),
            recent_messages.messages().to_vec(),
            episode_id,
        )
        .await;

    let event = build_result_event(info, status, summary, transcript_path, env.tz);
    if let Err(e) = env.publisher.publish(topics::Background, event).await {
        tracing::warn!(error = %e, "failed to publish session result to bus");
    }

    env.registry.remove(&info.address, &info.run_id);
    tracing::info!("session completed");

    if !leftover_messages.is_empty() {
        tracing::warn!(
            address = %info.address,
            count = leftover_messages.len(),
            "agent message(s) arrived as the run was tearing down; resuming the session as a new run to deliver them"
        );
        if let Err(e) = env
            .messenger
            .resume_with_messages(&info.address, &point, &leftover_messages)
            .await
        {
            tracing::error!(
                address = %info.address,
                error = %e,
                "failed to resume session to deliver messages queued at teardown"
            );
        }
    }
}

/// Build a [`SessionMemoryEnv`] borrowing from a run's [`SubAgentResources`],
/// for the two call sites (per-turn staging, final completion) that both
/// need one from the same fields.
fn session_memory_env(res: &SubAgentResources, tz: chrono_tz::Tz) -> SessionMemoryEnv<'_> {
    SessionMemoryEnv {
        observer: &res.observer,
        merge_writer: &res.merge_writer,
        layout: &res.layout,
        episode_skip_token_floor: res.episode_skip_token_floor,
        tz,
    }
}

/// A run's identity and resources, unchanging across however many turns the
/// run has — grouped so [`run_turn`] takes one borrow of them plus its own
/// per-turn arguments (the accumulated history, this turn's kickoff, and the
/// interrupt channel), rather than each individually.
struct TurnCtx<'a> {
    info: &'a SessionInfo,
    resources: Option<&'a SubAgentResources>,
    stop_token: &'a CancellationToken,
    store: &'a SessionStore,
}

/// Run one turn of a session's run, translating a missing-resources or
/// execution error into a `Failed` result rather than panicking or losing
/// the run.
///
/// `execute_subagent` returns `Ok` both when the turn finishes normally and
/// when it was stopped mid-flight (the stop token races the model call and
/// ends the turn at its next checkpoint rather than surfacing an error), so
/// an `Ok` alone cannot distinguish the two. Checking the token after the
/// fact tells them apart while still keeping whatever partial transcript
/// (left in `recent_messages`) the turn produced before it was stopped.
async fn run_turn(
    ctx: &TurnCtx<'_>,
    recent_messages: &mut RecentMessages,
    kickoff: TurnKickoff,
    interrupt_rx: &mut mpsc::Receiver<Interrupt>,
) -> (AgentResultStatus, String) {
    let sink = RunTranscriptSink {
        store: ctx.store,
        run_id: &ctx.info.run_id,
        started_at: ctx.info.started_at,
    };
    let outcome = async {
        let res = ctx
            .resources
            .ok_or_else(|| anyhow::anyhow!("session run requires SubAgentResources"))?;
        execute_subagent(
            &ctx.info.run_id,
            kickoff,
            recent_messages,
            res,
            ctx.stop_token,
            Some(&sink),
            interrupt_rx,
        )
        .await
    }
    .await;

    match outcome {
        Ok(summary) if ctx.stop_token.is_cancelled() => {
            tracing::info!("session turn stopped mid-flight");
            (AgentResultStatus::Cancelled, summary)
        }
        Ok(summary) => {
            tracing::info!("session turn completed");
            (AgentResultStatus::Completed, summary)
        }
        Err(e) => {
            tracing::warn!(error = %e, "session turn failed");
            (
                AgentResultStatus::Failed {
                    error: e.to_string(),
                },
                String::new(),
            )
        }
    }
}

/// Build the `AgentResultEvent` for a completed session run, computing its
/// disposition from sentinel strings the session leaves in its own summary.
///
/// `HEARTBEAT_OK` only silences a run driven by a pulse — the same rule the
/// background task bridge applied before sessions existed.
fn build_result_event(
    info: &SessionInfo,
    status: AgentResultStatus,
    summary: String,
    transcript_path: Option<std::path::PathBuf>,
    tz: chrono_tz::Tz,
) -> AgentResultEvent {
    let disposition =
        if matches!(info.trigger, EventTrigger::Pulse) && summary.contains(HEARTBEAT_OK) {
            ResultDisposition::Silent
        } else if summary.contains(HEARTBEAT_URGENT) {
            ResultDisposition::Urgent
        } else {
            ResultDisposition::Normal
        };

    AgentResultEvent {
        session_address: info.address.clone(),
        run_id: info.run_id.clone(),
        source_label: info.source_label.clone(),
        agent_skill: info.agent_skill.clone(),
        source: info.trigger.clone(),
        disposition,
        status,
        summary,
        transcript_path,
        timestamp: Utc::now().with_timezone(&tz).naive_local(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inference::{
        CompletionOptions, InferenceError, InferenceResponse, Message, ToolDefinition,
    };
    use crate::mcp::McpRegistry;
    use crate::skills::{SkillIndex, SkillState};
    use crate::workspace::identity::IdentityFiles;
    use async_trait::async_trait;

    use super::super::subagent::test_memory_extras;

    /// Build a runtime wired to a fresh in-process bus, returning it plus a
    /// subscriber for the `AgentResultEvent`s it publishes on completion.
    async fn test_runtime(
        max_concurrent: usize,
    ) -> (SessionRuntime, crate::bus::Subscriber<AgentResultEvent>) {
        let bus_handle = crate::bus::spawn_broker();
        let sub = bus_handle.subscribe(topics::Background).await.unwrap();
        let registry = Arc::new(SessionRegistry::new());
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(SessionStore::new(dir.path().to_path_buf()));
        let idle_timeouts = IdleTimeouts {
            scheduled: Duration::from_millis(20),
            spawned: Duration::from_millis(20),
            external: Duration::from_millis(20),
        };
        let messenger = Arc::new(AgentMessenger::new(
            Arc::clone(&registry),
            bus_handle.publisher(),
        ));
        let runtime = SessionRuntime::new(
            registry,
            store,
            max_concurrent,
            idle_timeouts,
            bus_handle.publisher(),
            chrono_tz::UTC,
            messenger,
        );
        (runtime, sub)
    }

    struct MockProvider {
        response: String,
    }

    #[async_trait]
    impl crate::inference::InferenceProvider for MockProvider {
        async fn complete(
            &self,
            _messages: &[Message],
            _tools: &[ToolDefinition],
            _options: &CompletionOptions,
        ) -> Result<InferenceResponse, InferenceError> {
            Ok(InferenceResponse::new(self.response.clone(), vec![]))
        }

        fn model_name(&self) -> &'static str {
            "mock"
        }
    }

    fn make_resources(response: &str) -> SubAgentResources {
        let (layout, observer, merge_writer) = test_memory_extras();
        SubAgentResources {
            provider: Box::new(MockProvider {
                response: response.to_string(),
            }),
            tools: crate::tools::ToolRegistry::new(),
            mcp_registry: McpRegistry::new_shared(),
            skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
            identity: IdentityFiles::default(),
            options: CompletionOptions::default(),
            skills_index: None,
            observations: None,
            recent_context: None,
            layout,
            observer,
            merge_writer,
            episode_skip_token_floor: 2000,
        }
    }

    fn sample_request(address: &str) -> SessionSpawnRequest {
        SessionSpawnRequest {
            address: SessionAddress::from(address),
            source_label: "agent:researcher".to_string(),
            trigger: EventTrigger::Agent,
            agent_skill: None,
            subagent_config: SubAgentConfig {
                prompt: "do the thing".to_string(),
                context: None,
                model_tier: crate::config::BackgroundModelTier::Medium,
            },
        }
    }

    #[tokio::test]
    async fn spawn_registers_session_immediately() {
        let (runtime, _sub) = test_runtime(3).await;
        runtime.spawn(sample_request("spawned-researcher-0001"), None);

        let live = runtime.registry.list_live();
        assert_eq!(live.len(), 1);
        let session = live.first().unwrap();
        assert_eq!(session.category, SessionCategory::Spawned);
        assert_eq!(session.depth, 1);
        assert_eq!(
            session.spawner,
            Some(SessionAddress::from(MAIN_ADDRESS)),
            "a session spawned by an agent should record main as its spawner in phase 1"
        );
    }

    #[tokio::test]
    async fn successful_run_goes_running_then_idle_then_completes() {
        let (runtime, mut sub) = test_runtime(3).await;
        let address = SessionAddress::from("spawned-researcher-0002");

        runtime.spawn(
            sample_request(address.as_ref()),
            Some(make_resources("all done")),
        );

        // Wait for the session to reach running or idle before it completes.
        let mut saw_running_or_idle = false;
        for _ in 0..50 {
            if let Some(info) = runtime.registry.get(&address)
                && matches!(info.state, SessionState::Running | SessionState::Idle)
            {
                saw_running_or_idle = true;
                break;
            }
            tokio::time::sleep(Duration::from_millis(2)).await;
        }
        assert!(saw_running_or_idle, "session should reach running or idle");

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("result should be published before test timeout")
            .unwrap()
            .unwrap();
        assert_eq!(event.summary, "all done");
        assert!(matches!(event.status, AgentResultStatus::Completed));

        // The session should no longer be listed once completed.
        assert!(runtime.registry.get(&address).is_none());

        // Its full transcript survives in the store.
        let transcript_path = event
            .transcript_path
            .expect("completed run should record a transcript path");
        let contents = tokio::fs::read_to_string(&transcript_path).await.unwrap();
        let record: serde_json::Value = serde_json::from_str(&contents).unwrap();
        assert_eq!(record.get("state").unwrap(), "completed");
        let transcript = record.get("transcript").unwrap().as_array().unwrap();
        assert!(
            transcript.len() >= 2,
            "transcript should hold at least the user prompt and the assistant reply"
        );
    }

    #[tokio::test]
    async fn missing_resources_produces_failed_result() {
        let (runtime, mut sub) = test_runtime(3).await;
        runtime.spawn(sample_request("spawned-researcher-0003"), None);

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .unwrap()
            .unwrap()
            .unwrap();
        assert!(matches!(event.status, AgentResultStatus::Failed { .. }));
    }

    #[tokio::test]
    async fn stop_before_permit_produces_cancelled_result() {
        // Zero concurrency: the session can never acquire a permit, so
        // stopping it must short-circuit straight to a cancelled result.
        let (runtime, mut sub) = test_runtime(0).await;
        let address = SessionAddress::from("spawned-researcher-0004");
        runtime.spawn(sample_request(address.as_ref()), None);
        assert!(runtime.registry.stop(&address));

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .unwrap()
            .unwrap()
            .unwrap();
        assert!(matches!(event.status, AgentResultStatus::Cancelled));
    }

    struct BlockingProvider;

    #[async_trait]
    impl crate::inference::InferenceProvider for BlockingProvider {
        async fn complete(
            &self,
            _messages: &[Message],
            _tools: &[ToolDefinition],
            _options: &CompletionOptions,
        ) -> Result<InferenceResponse, InferenceError> {
            std::future::pending().await
        }

        fn model_name(&self) -> &'static str {
            "blocking"
        }
    }

    #[tokio::test]
    async fn stop_during_running_turn_produces_cancelled_result() {
        // A provider that never returns keeps the turn stuck mid-flight so
        // the stop lands while the session is genuinely `running`, not
        // before the permit was even acquired.
        let (runtime, mut sub) = test_runtime(3).await;
        let address = SessionAddress::from("spawned-researcher-0005");
        let (layout, observer, merge_writer) = test_memory_extras();
        runtime.spawn(
            sample_request(address.as_ref()),
            Some(SubAgentResources {
                provider: Box::new(BlockingProvider),
                tools: crate::tools::ToolRegistry::new(),
                mcp_registry: McpRegistry::new_shared(),
                skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
                identity: IdentityFiles::default(),
                options: CompletionOptions::default(),
                skills_index: None,
                observations: None,
                recent_context: None,
                layout,
                observer,
                merge_writer,
                episode_skip_token_floor: 2000,
            }),
        );

        wait_for(&runtime, &address, Duration::from_secs(1), |info| {
            info.state == SessionState::Running
        })
        .await
        .expect("session should reach running while blocked on the model call");

        assert!(runtime.registry.stop(&address));

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("result should be published after the running turn is stopped")
            .unwrap()
            .unwrap();
        assert!(
            matches!(event.status, AgentResultStatus::Cancelled),
            "a session stopped mid-turn must report cancelled, not completed"
        );
    }

    #[tokio::test]
    async fn stop_with_a_pending_message_resumes_the_session_to_deliver_it() {
        // A message delivered while the turn is blocked on the model call
        // never reaches a tool-call checkpoint to be drained by the turn
        // itself. Stopping the session then must not let that message
        // vanish when `interrupt_rx` is dropped — `finish_run` drains it and
        // resumes the session as a new run instead.
        let bus_handle = crate::bus::spawn_broker();
        let mut result_sub: crate::bus::Subscriber<AgentResultEvent> =
            bus_handle.subscribe(topics::Background).await.unwrap();
        let mut spawn_sub: crate::bus::Subscriber<crate::bus::SpawnRequestEvent> =
            bus_handle.subscribe(topics::Background).await.unwrap();
        let registry = Arc::new(SessionRegistry::new());
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(SessionStore::new(dir.path().to_path_buf()));
        let messenger = Arc::new(AgentMessenger::new(
            Arc::clone(&registry),
            bus_handle.publisher(),
        ));
        let runtime = SessionRuntime::new(
            registry,
            store,
            3,
            IdleTimeouts {
                scheduled: Duration::from_secs(60),
                spawned: Duration::from_secs(60),
                external: Duration::from_secs(60),
            },
            bus_handle.publisher(),
            chrono_tz::UTC,
            messenger,
        );

        let address = SessionAddress::from("spawned-researcher-000t");
        let (layout, observer, merge_writer) = test_memory_extras();
        runtime.spawn(
            sample_request(address.as_ref()),
            Some(SubAgentResources {
                provider: Box::new(BlockingProvider),
                tools: crate::tools::ToolRegistry::new(),
                mcp_registry: McpRegistry::new_shared(),
                skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
                identity: IdentityFiles::default(),
                options: CompletionOptions::default(),
                skills_index: None,
                observations: None,
                recent_context: None,
                layout,
                observer,
                merge_writer,
                episode_skip_token_floor: 2000,
            }),
        );

        wait_for(&runtime, &address, Duration::from_secs(1), |info| {
            info.state == SessionState::Running
        })
        .await
        .expect("session should reach running while blocked on the model call");

        assert_eq!(
            runtime.registry.deliver(
                &address,
                Interrupt::AgentMessage(AgentMessageEvent {
                    from: SessionAddress::from(MAIN_ADDRESS),
                    from_category: "main".to_string(),
                    content: "don't forget this".to_string(),
                    hop_count: 0,
                }),
            ),
            crate::background::registry::DeliverOutcome::Delivered
        );

        assert!(runtime.registry.stop(&address));

        let result_event = tokio::time::timeout(Duration::from_secs(2), result_sub.recv())
            .await
            .expect("stopped run should still publish a result")
            .unwrap()
            .unwrap();
        assert!(matches!(result_event.status, AgentResultStatus::Cancelled));

        let spawn_event = tokio::time::timeout(Duration::from_secs(2), spawn_sub.recv())
            .await
            .expect("the pending message must resume the session as a new run rather than vanish")
            .unwrap()
            .unwrap();
        assert_eq!(spawn_event.address, address);
        assert!(spawn_event.prompt.contains("don't forget this"));
    }

    struct PanickingProvider;

    #[async_trait]
    impl crate::inference::InferenceProvider for PanickingProvider {
        async fn complete(
            &self,
            _messages: &[Message],
            _tools: &[ToolDefinition],
            _options: &CompletionOptions,
        ) -> Result<InferenceResponse, InferenceError> {
            panic!("intentional provider panic for test coverage");
        }

        fn model_name(&self) -> &'static str {
            "panicking"
        }
    }

    #[tokio::test]
    async fn panicking_turn_still_publishes_failed_result_and_frees_registry() {
        let (runtime, mut sub) = test_runtime(3).await;
        let address = SessionAddress::from("spawned-researcher-0006");
        let (layout, observer, merge_writer) = test_memory_extras();
        runtime.spawn(
            sample_request(address.as_ref()),
            Some(SubAgentResources {
                provider: Box::new(PanickingProvider),
                tools: crate::tools::ToolRegistry::new(),
                mcp_registry: McpRegistry::new_shared(),
                skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
                identity: IdentityFiles::default(),
                options: CompletionOptions::default(),
                skills_index: None,
                observations: None,
                recent_context: None,
                layout,
                observer,
                merge_writer,
                episode_skip_token_floor: 2000,
            }),
        );

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("a panicked session must still publish a result")
            .unwrap()
            .unwrap();
        assert!(
            matches!(event.status, AgentResultStatus::Failed { .. }),
            "a panicked turn should be reported as failed, got {:?}",
            event.status
        );
        assert!(
            runtime.registry.get(&address).is_none(),
            "a panicked session must not linger in the registry forever"
        );

        let transcript_path = event
            .transcript_path
            .expect("a panicked run should still record a transcript path");
        let contents = tokio::fs::read_to_string(&transcript_path).await.unwrap();
        let record: serde_json::Value = serde_json::from_str(&contents).unwrap();
        let transcript = record.get("transcript").unwrap().as_array().unwrap();
        assert!(
            !transcript.is_empty(),
            "the pre-panic transcript (the initial user message, durably \
             sink-appended before the provider call panicked) must be \
             backfilled from the transcript sidecar rather than discarded"
        );
    }

    #[tokio::test]
    async fn recover_from_panic_backfills_and_merges_a_substantial_transcript() {
        // Drives `recover_from_panic` directly against a store whose
        // incremental transcript sidecar already holds substantial content —
        // the same durable file a real panic mid-turn would have left behind
        // — to prove the panic path backfills the transcript and runs the
        // normal completion memory pipeline instead of always reporting an
        // empty transcript with no episode.
        let dir = tempfile::tempdir().unwrap();
        let store = SessionStore::new(dir.path().to_path_buf());
        let info = SessionInfo {
            address: SessionAddress::from("spawned-researcher-0006b"),
            run_id: "run-panic-substantial".to_string(),
            category: SessionCategory::Spawned,
            trigger: EventTrigger::Agent,
            source_label: "agent:researcher".to_string(),
            state: SessionState::Running,
            spawner: Some(SessionAddress::from(MAIN_ADDRESS)),
            depth: 1,
            purpose: "research the thing".to_string(),
            agent_skill: None,
            model_tier: crate::config::BackgroundModelTier::Medium,
            started_at: Utc::now(),
        };
        store.begin_run(&info).await;

        let big_content = "a".repeat(9000);
        store
            .append_transcript(
                &info.run_id,
                info.started_at,
                &[
                    Message::user("investigate the issue"),
                    Message::assistant(big_content, None),
                ],
            )
            .await;

        let layout = crate::workspace::layout::WorkspaceLayout::new(dir.path());
        let search_index = std::sync::Arc::new(
            crate::memory::search::MemoryIndex::open_or_create(&layout.search_index_dir()).unwrap(),
        );
        let reflector = crate::memory::reflector::Reflector::disabled(chrono_tz::UTC);
        let merge_writer = Arc::new(crate::memory::merge_writer::MemoryMergeWriter::new(
            reflector,
            layout.clone(),
            search_index,
            None,
            None,
        ));
        let observer = Arc::new(crate::memory::observer::Observer::new(
            Box::new(crate::memory::test_helpers::MockMemoryProvider::new(
                r#"{"observations": [{"content": "recovered from a panic", "timestamp": "2026-02-21T14:30", "visibility": "background"}]}"#,
            )),
            crate::memory::observer::ObserverConfig::default(),
        ));
        let mem_extras = PanicMemoryExtras {
            observer,
            merge_writer,
            layout,
            episode_skip_token_floor: 2000,
        };

        let registry = SessionRegistry::new();
        let _rx = registry.register(info.clone(), CancellationToken::new());
        let bus_handle = crate::bus::spawn_broker();
        let mut sub: crate::bus::Subscriber<AgentResultEvent> =
            bus_handle.subscribe(topics::Background).await.unwrap();
        let publisher = bus_handle.publisher();

        recover_from_panic(
            &info,
            &registry,
            &store,
            &publisher,
            chrono_tz::UTC,
            "intentional panic for test coverage",
            Some(mem_extras),
        )
        .await;

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("panic recovery should publish a result")
            .unwrap()
            .unwrap();
        assert!(matches!(event.status, AgentResultStatus::Failed { .. }));
        assert!(
            registry.get(&info.address).is_none(),
            "panic recovery must remove the session from the registry"
        );

        let transcript_path = event
            .transcript_path
            .expect("panic recovery should still record a transcript path");
        let contents = tokio::fs::read_to_string(&transcript_path).await.unwrap();
        let record: serde_json::Value = serde_json::from_str(&contents).unwrap();
        let transcript = record.get("transcript").unwrap().as_array().unwrap();
        assert_eq!(
            transcript.len(),
            2,
            "the pre-panic transcript must be backfilled from the sidecar file"
        );
        assert!(
            record.get("episode_id").unwrap().is_string(),
            "a substantial pre-panic transcript should still be merged into an episode, got {record:?}"
        );
    }

    #[tokio::test]
    async fn shutdown_stops_live_sessions_and_waits_for_completion() {
        let (runtime, mut sub) = test_runtime(3).await;
        let address = SessionAddress::from("spawned-researcher-0007");
        let (layout, observer, merge_writer) = test_memory_extras();
        runtime.spawn(
            sample_request(address.as_ref()),
            Some(SubAgentResources {
                provider: Box::new(BlockingProvider),
                tools: crate::tools::ToolRegistry::new(),
                mcp_registry: McpRegistry::new_shared(),
                skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
                identity: IdentityFiles::default(),
                options: CompletionOptions::default(),
                skills_index: None,
                observations: None,
                recent_context: None,
                layout,
                observer,
                merge_writer,
                episode_skip_token_floor: 2000,
            }),
        );

        wait_for(&runtime, &address, Duration::from_secs(1), |info| {
            info.state == SessionState::Running
        })
        .await
        .expect("session should reach running before shutdown stops it");

        runtime.shutdown(Duration::from_secs(2)).await;

        assert!(
            runtime.registry.get(&address).is_none(),
            "shutdown should wait for the stopped session to finish completing"
        );
        let event = tokio::time::timeout(Duration::from_millis(200), sub.recv())
            .await
            .expect("shutdown should have let the session publish its result")
            .unwrap()
            .unwrap();
        assert!(matches!(event.status, AgentResultStatus::Cancelled));
    }

    #[tokio::test]
    async fn shutdown_with_no_live_sessions_returns_immediately() {
        let (runtime, _sub) = test_runtime(3).await;
        tokio::time::timeout(
            Duration::from_millis(100),
            runtime.shutdown(Duration::from_secs(5)),
        )
        .await
        .expect("shutdown must not block when there is nothing to stop");
    }

    #[tokio::test]
    async fn idle_session_releases_its_permit_for_a_new_run() {
        // max_concurrent = 1: if an idle session held its permit, a second
        // session could not start running until the first's idle timeout
        // elapsed. Give the first session an idle window long enough that
        // waiting it out would be obviously slow, then prove the second
        // reaches running/idle almost immediately instead.
        let idle_window = Duration::from_millis(300);
        let bus_handle = crate::bus::spawn_broker();
        let registry = Arc::new(SessionRegistry::new());
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(SessionStore::new(dir.path().to_path_buf()));
        let messenger = Arc::new(AgentMessenger::new(
            Arc::clone(&registry),
            bus_handle.publisher(),
        ));
        let runtime = SessionRuntime::new(
            registry,
            store,
            1,
            IdleTimeouts {
                scheduled: idle_window,
                spawned: idle_window,
                external: idle_window,
            },
            bus_handle.publisher(),
            chrono_tz::UTC,
            messenger,
        );

        let first = SessionAddress::from("spawned-first-0001");
        runtime.spawn(
            sample_request(first.as_ref()),
            Some(make_resources("first done")),
        );

        // Wait for the first session to go idle (releasing its permit).
        let idle_at = wait_for(&runtime, &first, Duration::from_secs(1), |info| {
            info.state == SessionState::Idle
        })
        .await
        .expect("first session should reach idle");

        let second = SessionAddress::from("spawned-second-0002");
        runtime.spawn(
            sample_request(second.as_ref()),
            Some(make_resources("second done")),
        );
        // Any state past `Forking` means the permit was acquired and the
        // turn at least started — must happen well inside the first
        // session's idle window to prove it didn't wait on that timeout.
        let second_started = wait_for(&runtime, &second, idle_window, |info| {
            info.state != SessionState::Forking
        })
        .await;
        let elapsed = idle_at.elapsed();
        assert!(
            second_started.is_some(),
            "second session should start running without waiting for the first's idle timeout \
             (waited {elapsed:?} against an idle window of {idle_window:?})"
        );
    }

    /// Poll a runtime's registry until `address`'s info satisfies `pred`, or the deadline elapses.
    async fn wait_for(
        runtime: &SessionRuntime,
        address: &SessionAddress,
        deadline: Duration,
        pred: impl Fn(&SessionInfo) -> bool,
    ) -> Option<std::time::Instant> {
        let start = std::time::Instant::now();
        while start.elapsed() < deadline {
            if let Some(info) = runtime.registry.get(address)
                && pred(&info)
            {
                return Some(std::time::Instant::now());
            }
            tokio::time::sleep(Duration::from_millis(2)).await;
        }
        None
    }

    #[test]
    fn idle_timeouts_use_scheduled_timeout_for_webhooks() {
        let timeouts = IdleTimeouts {
            scheduled: Duration::from_mins(2),
            spawned: Duration::from_mins(10),
            external: Duration::from_mins(30),
        };
        assert_eq!(
            timeouts.for_trigger(&EventTrigger::Webhook("gh".into())),
            Duration::from_mins(2),
            "a webhook call is one-shot, so it uses the scheduled timeout"
        );
        assert_eq!(
            timeouts.for_trigger(&EventTrigger::Pulse),
            Duration::from_mins(2)
        );
        assert_eq!(
            timeouts.for_trigger(&EventTrigger::Agent),
            Duration::from_mins(10)
        );
    }

    #[test]
    fn build_result_event_silences_only_pulse_heartbeat_ok() {
        let info = SessionInfo {
            address: SessionAddress::from("scheduled-check-0001"),
            run_id: "run-1".to_string(),
            category: SessionCategory::Scheduled,
            trigger: EventTrigger::Pulse,
            source_label: "pulse:check".to_string(),
            state: SessionState::Completing,
            spawner: None,
            depth: 1,
            purpose: "check things".to_string(),
            agent_skill: None,
            model_tier: crate::config::BackgroundModelTier::Medium,
            started_at: Utc::now(),
        };
        let event = build_result_event(
            &info,
            AgentResultStatus::Completed,
            HEARTBEAT_OK.to_string(),
            None,
            chrono_tz::UTC,
        );
        assert_eq!(event.disposition, ResultDisposition::Silent);

        let mut action_info = info.clone();
        action_info.trigger = EventTrigger::Action;
        let action_event = build_result_event(
            &action_info,
            AgentResultStatus::Completed,
            HEARTBEAT_OK.to_string(),
            None,
            chrono_tz::UTC,
        );
        assert_eq!(
            action_event.disposition,
            ResultDisposition::Normal,
            "HEARTBEAT_OK only silences pulse-triggered runs"
        );
    }

    #[test]
    fn build_result_event_tags_session_address_and_run_id() {
        let info = SessionInfo {
            address: SessionAddress::from("spawned-researcher-0007"),
            run_id: "run-7".to_string(),
            category: SessionCategory::Spawned,
            trigger: EventTrigger::Agent,
            source_label: "agent:researcher".to_string(),
            state: SessionState::Completing,
            spawner: Some(SessionAddress::from(MAIN_ADDRESS)),
            depth: 1,
            purpose: "research".to_string(),
            agent_skill: None,
            model_tier: crate::config::BackgroundModelTier::Medium,
            started_at: Utc::now(),
        };
        let event = build_result_event(
            &info,
            AgentResultStatus::Completed,
            "found it".to_string(),
            None,
            chrono_tz::UTC,
        );
        assert_eq!(event.session_address, info.address);
        assert_eq!(event.run_id, "run-7");
    }

    /// Provider that returns canned responses in sequence, one per call —
    /// unlike `MockProvider`, which always returns the same response — so a
    /// test can distinguish a run's first turn from its second.
    struct SequencedProvider {
        responses: Vec<String>,
        call_count: std::sync::atomic::AtomicUsize,
    }

    impl SequencedProvider {
        fn new(responses: Vec<&str>) -> Self {
            Self {
                responses: responses.into_iter().map(str::to_string).collect(),
                call_count: std::sync::atomic::AtomicUsize::new(0),
            }
        }
    }

    #[async_trait]
    impl crate::inference::InferenceProvider for SequencedProvider {
        async fn complete(
            &self,
            _messages: &[Message],
            _tools: &[ToolDefinition],
            _options: &CompletionOptions,
        ) -> Result<InferenceResponse, InferenceError> {
            let idx = self
                .call_count
                .fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            let response = self
                .responses
                .get(idx)
                .cloned()
                .unwrap_or_else(|| "no more responses configured".to_string());
            Ok(InferenceResponse::new(response, vec![]))
        }

        fn model_name(&self) -> &'static str {
            "sequenced"
        }
    }

    fn make_sequenced_resources(responses: Vec<&str>) -> SubAgentResources {
        let (layout, observer, merge_writer) = test_memory_extras();
        SubAgentResources {
            provider: Box::new(SequencedProvider::new(responses)),
            tools: crate::tools::ToolRegistry::new(),
            mcp_registry: McpRegistry::new_shared(),
            skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
            identity: IdentityFiles::default(),
            options: CompletionOptions::default(),
            skills_index: None,
            observations: None,
            recent_context: None,
            layout,
            observer,
            merge_writer,
            episode_skip_token_floor: 2000,
        }
    }

    /// Build a runtime with a longer, fixed idle window (rather than
    /// `test_runtime`'s 20ms) so a test has a reliable window to deliver a
    /// message while the session is genuinely idle, without racing a
    /// timeout that would complete the run out from under it.
    async fn test_runtime_with_idle_window(
        idle_window: Duration,
    ) -> (SessionRuntime, crate::bus::Subscriber<AgentResultEvent>) {
        let bus_handle = crate::bus::spawn_broker();
        let sub = bus_handle.subscribe(topics::Background).await.unwrap();
        let registry = Arc::new(SessionRegistry::new());
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(SessionStore::new(dir.path().to_path_buf()));
        let messenger = Arc::new(AgentMessenger::new(
            Arc::clone(&registry),
            bus_handle.publisher(),
        ));
        let runtime = SessionRuntime::new(
            registry,
            store,
            3,
            IdleTimeouts {
                scheduled: idle_window,
                spawned: idle_window,
                external: idle_window,
            },
            bus_handle.publisher(),
            chrono_tz::UTC,
            messenger,
        );
        (runtime, sub)
    }

    #[tokio::test]
    async fn wait_idle_treats_a_message_racing_the_timeout_as_a_wake() {
        // A zero-length idle window is already elapsed the instant the
        // future is first polled, so the biased select's timeout arm can win
        // even with a message already sitting in the channel — exactly the
        // race `wait_idle`'s post-timeout `try_recv` exists to catch.
        let (tx, mut rx) = mpsc::channel(4);
        tx.try_send(Interrupt::AgentMessage(AgentMessageEvent {
            from: SessionAddress::from(MAIN_ADDRESS),
            from_category: "main".to_string(),
            content: "just in time".to_string(),
            hop_count: 0,
        }))
        .unwrap();

        let stop_token = CancellationToken::new();
        match wait_idle(&stop_token, Duration::ZERO, &mut rx).await {
            IdleOutcome::Woken(msg) => assert_eq!(msg.content, "just in time"),
            IdleOutcome::TimedOut => panic!(
                "a message already queued when the timeout fired must still wake the session"
            ),
            IdleOutcome::Stopped => panic!("stop token was never cancelled"),
        }
    }

    #[tokio::test]
    async fn wait_idle_times_out_when_the_channel_is_genuinely_empty() {
        let (_tx, mut rx) = mpsc::channel(4);
        let stop_token = CancellationToken::new();
        assert!(matches!(
            wait_idle(&stop_token, Duration::from_millis(5), &mut rx).await,
            IdleOutcome::TimedOut
        ));
    }

    #[tokio::test]
    async fn idle_session_wakes_for_agent_message_and_runs_a_second_turn() {
        let (runtime, mut sub) = test_runtime_with_idle_window(Duration::from_millis(300)).await;
        let address = SessionAddress::from("spawned-researcher-0008");
        runtime.spawn(
            sample_request(address.as_ref()),
            Some(make_sequenced_resources(vec!["first done", "second done"])),
        );

        wait_for(&runtime, &address, Duration::from_secs(1), |info| {
            info.state == SessionState::Idle
        })
        .await
        .expect("session should go idle after its first turn");

        // Exactly what `AgentMessenger::send` does to deliver to a live
        // session — see `crate::background::messaging`.
        assert_eq!(
            runtime.registry.deliver(
                &address,
                Interrupt::AgentMessage(AgentMessageEvent {
                    from: SessionAddress::from(MAIN_ADDRESS),
                    from_category: "main".to_string(),
                    content: "any updates?".to_string(),
                    hop_count: 0,
                }),
            ),
            crate::background::registry::DeliverOutcome::Delivered,
            "the idle session should still be live in the registry"
        );

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("the run should eventually complete")
            .unwrap()
            .unwrap();
        assert_eq!(
            event.summary, "second done",
            "the run should complete with its second turn's own summary"
        );

        let transcript_path = event
            .transcript_path
            .expect("completed run should have a transcript");
        let contents = tokio::fs::read_to_string(&transcript_path).await.unwrap();
        let record: serde_json::Value = serde_json::from_str(&contents).unwrap();
        let transcript = record.get("transcript").unwrap().as_array().unwrap();
        let joined: String = transcript
            .iter()
            .filter_map(|m| m.get("content").and_then(|c| c.as_str()))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            joined.contains("first done"),
            "transcript should keep the first turn's output: {joined}"
        );
        assert!(
            joined.contains("any updates?"),
            "transcript should record the delivered agent message: {joined}"
        );
        assert!(
            joined.contains("second done"),
            "transcript should include the second turn's output: {joined}"
        );

        // One run, one completion — the wake extended the existing run
        // rather than starting a new one.
        assert!(
            tokio::time::timeout(Duration::from_millis(150), sub.recv())
                .await
                .is_err(),
            "a single message-driven wake should not produce a second run"
        );
    }

    /// `SubAgentResources` built with a real (non-disabled) observer whose
    /// thresholds are set to fire on essentially any content, paired with a
    /// mock provider that always finds one observation — so a turn's
    /// messages always cross the force threshold and get staged.
    fn make_sequenced_resources_with_eager_observer(
        responses: Vec<&str>,
    ) -> (SubAgentResources, crate::workspace::layout::WorkspaceLayout) {
        let dir = tempfile::tempdir().unwrap().keep();
        let layout = crate::workspace::layout::WorkspaceLayout::new(&dir);
        let search_index = Arc::new(
            crate::memory::search::MemoryIndex::open_or_create(&layout.search_index_dir()).unwrap(),
        );
        let reflector = crate::memory::reflector::Reflector::disabled(chrono_tz::UTC);
        let merge_writer = Arc::new(crate::memory::merge_writer::MemoryMergeWriter::new(
            reflector,
            layout.clone(),
            search_index,
            None,
            None,
        ));
        let observer = Arc::new(crate::memory::observer::Observer::new(
            Box::new(crate::memory::test_helpers::MockMemoryProvider::new(
                r#"{"observations": [{"content": "staged a finding", "timestamp": "2026-02-21T14:30", "visibility": "background"}]}"#,
            )),
            crate::memory::observer::ObserverConfig {
                threshold_tokens: 1,
                force_threshold_tokens: 1,
                ..crate::memory::observer::ObserverConfig::default()
            },
        ));
        let resources = SubAgentResources {
            provider: Box::new(SequencedProvider::new(responses)),
            tools: crate::tools::ToolRegistry::new(),
            mcp_registry: McpRegistry::new_shared(),
            skill_state: SkillState::new_shared(SkillIndex::default(), vec![]),
            identity: IdentityFiles::default(),
            options: CompletionOptions::default(),
            skills_index: None,
            observations: None,
            recent_context: None,
            layout: layout.clone(),
            observer,
            merge_writer,
            episode_skip_token_floor: 2000,
        };
        (resources, layout)
    }

    #[tokio::test]
    async fn staging_runs_after_every_turn_not_just_once() {
        let (runtime, mut sub) = test_runtime_with_idle_window(Duration::from_millis(300)).await;
        let address = SessionAddress::from("spawned-researcher-0009");
        let (resources, layout) = make_sequenced_resources_with_eager_observer(vec![
            "first turn done",
            "second turn done",
        ]);
        runtime.spawn(sample_request(address.as_ref()), Some(resources));

        wait_for(&runtime, &address, Duration::from_secs(1), |info| {
            info.state == SessionState::Idle
        })
        .await
        .expect("session should go idle after its first turn");

        assert_eq!(
            runtime.registry.deliver(
                &address,
                Interrupt::AgentMessage(AgentMessageEvent {
                    from: SessionAddress::from(MAIN_ADDRESS),
                    from_category: "main".to_string(),
                    content: "keep going".to_string(),
                    hop_count: 0,
                }),
            ),
            crate::background::registry::DeliverOutcome::Delivered
        );

        let event = tokio::time::timeout(Duration::from_secs(2), sub.recv())
            .await
            .expect("the run should eventually complete")
            .unwrap()
            .unwrap();
        assert_eq!(event.summary, "second turn done");

        // Each turn crossed the (tiny) force threshold on its own and staged
        // its own observation — if staging only ran once, at the end, there
        // would be one merged observation here, not two.
        let log = crate::memory::log_store::load_observation_log(&layout.observations_json())
            .await
            .unwrap();
        let matching = log
            .observations
            .iter()
            .filter(|o| o.source.session_address.as_deref() == Some(address.as_ref()))
            .count();
        assert_eq!(
            matching, 2,
            "each of the run's two turns should have staged its own observation"
        );
    }
}
