//! Turn and session token-usage aggregation for the web UI's activity line
//! and conversation size.
//!
//! Usage is tracked and published purely for people watching the web UI: a
//! running turn's activity line (elapsed time and tokens so far) and the
//! conversation size (cumulative session totals). It is never added to the agent's own
//! status line, context, or tool results — a visible token/time budget
//! would push the agent to stop long-running work early. See
//! `docs/systems-usage/turn-control.md`.

use std::path::Path;
use std::sync::Arc;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;
use ts_rs::TS;

use crate::inference::Usage;

/// Token usage accumulated across the model calls made so far in a turn
/// that's still running. Reset at the start of every turn; never persisted
/// — the activity line only cares about progress within the
/// current turn.
#[derive(Debug, Clone, Copy, Default)]
pub struct TurnUsage {
    /// Output tokens generated by every model call so far this turn.
    pub output_tokens: u32,
    /// Whether any model call so far this turn reported usage. When
    /// `false`, the web UI shows elapsed time alone rather than a
    /// misleading zero-token count.
    pub has_usage: bool,
    /// Tool calls executed so far this turn. Every tool call an executed
    /// batch carries counts individually, including calls made in parallel
    /// within the same model response.
    pub tool_calls: u32,
}

impl TurnUsage {
    /// Fold one model call's usage into this turn's running total. A `None`
    /// usage (a provider that didn't report any) leaves the total
    /// unchanged.
    pub fn accumulate(&mut self, usage: Option<Usage>) {
        let Some(usage) = usage else {
            return;
        };
        self.has_usage = true;
        self.output_tokens += usage.output_tokens;
    }

    /// Fold `n` more executed tool calls into this turn's running count.
    pub fn record_tool_calls(&mut self, n: u32) {
        self.tool_calls += n;
    }
}

/// Cumulative token totals for a whole session (the main chat, or one
/// background session run), persisted so a reload shows correct totals
/// rather than resetting to zero. See `docs/systems-usage/turn-control.md`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct SessionUsageTotals {
    /// Prompt tokens sent across every model call this session has made.
    #[ts(type = "number")]
    pub input_tokens: u64,
    /// Completion tokens generated across every model call this session
    /// has made.
    #[ts(type = "number")]
    pub output_tokens: u64,
    /// Context size at the most recent model call: that call's input
    /// tokens plus its cache reads/writes — the actual token count the
    /// provider processed as context, not an estimate. `None` until the
    /// first call that reports usage. There is no per-model context-window
    /// size known to the codebase, so this is shown as an absolute count
    /// rather than a percentage.
    pub context_tokens: Option<u32>,
    /// Tool calls executed across every turn this session has run. Every
    /// tool call an executed batch carries counts individually, including
    /// calls made in parallel within the same model response.
    ///
    /// `#[serde(default)]` so a totals file or run record persisted before
    /// this field existed still deserializes, showing zero rather than
    /// failing to load.
    #[serde(default)]
    #[ts(type = "number")]
    pub tool_calls: u64,
}

impl SessionUsageTotals {
    /// Fold one model call's usage into these running totals. A `None`
    /// usage (a provider that didn't report any) leaves them unchanged.
    pub fn accumulate(&mut self, usage: Option<Usage>) {
        let Some(usage) = usage else {
            return;
        };
        self.input_tokens += u64::from(usage.input_tokens);
        self.output_tokens += u64::from(usage.output_tokens);
        self.context_tokens = Some(
            usage.input_tokens
                + usage.cache_creation_tokens.unwrap_or(0)
                + usage.cache_read_tokens.unwrap_or(0),
        );
    }

    /// Fold `n` more executed tool calls into these running totals.
    pub fn record_tool_calls(&mut self, n: u32) {
        self.tool_calls += u64::from(n);
    }
}

/// Where a turn's session-level usage totals are durably accumulated: the
/// main agent's own workspace file ([`MainUsageSink`]), or a background
/// session's registry entry (mirrored into its store record at
/// completion — see `crate::background::registry::SessionUsageSink`).
/// Mirrors [`crate::agent::turn::TranscriptSink`]'s split between the main
/// agent's own persistence and a session's.
#[async_trait]
pub trait UsageSink: Send + Sync {
    /// Fold one model call's usage into the durable running totals and
    /// return the updated totals, for publishing alongside this turn's own
    /// progress.
    async fn accumulate(&self, usage: Option<Usage>) -> SessionUsageTotals;

    /// Fold `n` more executed tool calls into the durable running totals
    /// and return the updated totals, for publishing alongside this turn's
    /// own progress.
    async fn record_tool_calls(&self, n: u32) -> SessionUsageTotals;
}

/// Load previously persisted session usage totals.
///
/// Returns the default (all zero) if the file doesn't exist yet, or if it
/// fails to read or parse — a missing or corrupt totals file only means the
/// conversation size starts from zero, never a fatal startup error, so the failure is
/// logged at `warn` rather than propagated.
pub async fn load_session_usage_totals(path: &Path) -> SessionUsageTotals {
    match tokio::fs::read_to_string(path).await {
        Ok(contents) if contents.trim().is_empty() => SessionUsageTotals::default(),
        Ok(contents) => serde_json::from_str(&contents).unwrap_or_else(|e| {
            tracing::warn!(
                error = %e,
                path = %path.display(),
                "failed to parse persisted usage totals; starting from zero"
            );
            SessionUsageTotals::default()
        }),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => SessionUsageTotals::default(),
        Err(e) => {
            tracing::warn!(
                error = %e,
                path = %path.display(),
                "failed to read persisted usage totals; starting from zero"
            );
            SessionUsageTotals::default()
        }
    }
}

/// Persist session usage totals. Logs at `warn` and returns without error on
/// failure — a missed write only means the next restart's conversation size starts
/// from a slightly stale total, never a reason to fail the turn that
/// produced it.
pub async fn save_session_usage_totals(path: &Path, totals: &SessionUsageTotals) {
    let json = match serde_json::to_string(totals) {
        Ok(j) => j,
        Err(e) => {
            tracing::warn!(error = %e, "failed to serialize usage totals");
            return;
        }
    };
    if let Err(e) = tokio::fs::write(path, json).await {
        tracing::warn!(error = %e, path = %path.display(), "failed to persist usage totals");
    }
}

/// The main agent's own [`UsageSink`]: an in-memory running total shared
/// with the `Agent` that owns it (so every turn accumulates onto the same
/// totals), written through to disk after every model call so a restart
/// resumes with the right totals instead of resetting to zero.
pub struct MainUsageSink {
    totals: Arc<Mutex<SessionUsageTotals>>,
    /// `None` for an agent with no workspace layout (test constructors) —
    /// totals then live only in memory for the process's lifetime.
    persist_path: Option<std::path::PathBuf>,
}

impl MainUsageSink {
    /// Wrap the agent's own shared totals for one turn's use.
    #[must_use]
    pub fn new(
        totals: Arc<Mutex<SessionUsageTotals>>,
        persist_path: Option<std::path::PathBuf>,
    ) -> Self {
        Self {
            totals,
            persist_path,
        }
    }
}

#[async_trait]
impl UsageSink for MainUsageSink {
    async fn accumulate(&self, usage: Option<Usage>) -> SessionUsageTotals {
        let snapshot = {
            let mut guard = self.totals.lock().await;
            guard.accumulate(usage);
            *guard
        };
        if let Some(path) = &self.persist_path {
            save_session_usage_totals(path, &snapshot).await;
        }
        snapshot
    }

    async fn record_tool_calls(&self, n: u32) -> SessionUsageTotals {
        let snapshot = {
            let mut guard = self.totals.lock().await;
            guard.record_tool_calls(n);
            *guard
        };
        if let Some(path) = &self.persist_path {
            save_session_usage_totals(path, &snapshot).await;
        }
        snapshot
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn usage(input: u32, output: u32) -> Usage {
        Usage {
            input_tokens: input,
            output_tokens: output,
            cache_creation_tokens: None,
            cache_read_tokens: None,
        }
    }

    #[test]
    fn turn_usage_accumulates_output_tokens_across_calls() {
        let mut turn = TurnUsage::default();
        turn.accumulate(Some(usage(100, 20)));
        turn.accumulate(Some(usage(150, 30)));
        assert_eq!(turn.output_tokens, 50);
        assert!(turn.has_usage);
    }

    #[test]
    fn turn_usage_none_leaves_totals_unchanged_but_not_marked_has_usage() {
        let mut turn = TurnUsage::default();
        turn.accumulate(None);
        assert_eq!(turn.output_tokens, 0);
        assert!(
            !turn.has_usage,
            "a provider reporting no usage must not flip has_usage"
        );
    }

    #[test]
    fn turn_usage_has_usage_stays_true_once_set_even_if_a_later_call_has_none() {
        let mut turn = TurnUsage::default();
        turn.accumulate(Some(usage(10, 5)));
        turn.accumulate(None);
        assert!(
            turn.has_usage,
            "one call with usage is enough to know some usage occurred"
        );
        assert_eq!(
            turn.output_tokens, 5,
            "the None call must not erase prior totals"
        );
    }

    #[test]
    fn turn_usage_record_tool_calls_accumulates_across_batches() {
        let mut turn = TurnUsage::default();
        turn.record_tool_calls(3);
        turn.record_tool_calls(2);
        assert_eq!(turn.tool_calls, 5);
    }

    #[test]
    fn turn_usage_with_zero_tool_calls_stays_zero() {
        let turn = TurnUsage::default();
        assert_eq!(turn.tool_calls, 0);
    }

    #[test]
    fn session_usage_totals_accumulate_input_and_output() {
        let mut totals = SessionUsageTotals::default();
        totals.accumulate(Some(usage(100, 20)));
        totals.accumulate(Some(usage(150, 30)));
        assert_eq!(totals.input_tokens, 250);
        assert_eq!(totals.output_tokens, 50);
    }

    #[test]
    fn session_usage_totals_context_tokens_is_the_latest_calls_full_context() {
        let mut totals = SessionUsageTotals::default();
        totals.accumulate(Some(Usage {
            input_tokens: 100,
            output_tokens: 20,
            cache_creation_tokens: Some(10),
            cache_read_tokens: Some(5),
        }));
        assert_eq!(totals.context_tokens, Some(115));
        totals.accumulate(Some(usage(40, 10)));
        assert_eq!(
            totals.context_tokens,
            Some(40),
            "context size reflects only the most recent call, not a running sum"
        );
    }

    #[test]
    fn session_usage_totals_none_leaves_everything_unchanged() {
        let mut totals = SessionUsageTotals::default();
        totals.accumulate(Some(usage(100, 20)));
        totals.accumulate(None);
        assert_eq!(totals.input_tokens, 100);
        assert_eq!(totals.output_tokens, 20);
        assert_eq!(totals.context_tokens, Some(100));
    }

    #[test]
    fn session_usage_totals_record_tool_calls_accumulates() {
        let mut totals = SessionUsageTotals::default();
        totals.record_tool_calls(4);
        totals.record_tool_calls(6);
        assert_eq!(totals.tool_calls, 10);
    }

    #[test]
    fn session_usage_totals_deserializes_a_payload_persisted_before_tool_calls_existed() {
        let old_payload = serde_json::json!({
            "input_tokens": 100,
            "output_tokens": 20,
            "context_tokens": 100,
        });
        let totals: SessionUsageTotals = serde_json::from_value(old_payload).unwrap();
        assert_eq!(totals.input_tokens, 100);
        assert_eq!(totals.output_tokens, 20);
        assert_eq!(totals.context_tokens, Some(100));
        assert_eq!(
            totals.tool_calls, 0,
            "a payload persisted before tool_calls existed should default to zero, not fail to parse"
        );
    }

    #[tokio::test]
    async fn load_session_usage_totals_missing_file_returns_default() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage_totals.json");
        let totals = load_session_usage_totals(&path).await;
        assert_eq!(totals, SessionUsageTotals::default());
    }

    #[tokio::test]
    async fn load_session_usage_totals_corrupt_file_returns_default() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage_totals.json");
        tokio::fs::write(&path, "not json").await.unwrap();
        let totals = load_session_usage_totals(&path).await;
        assert_eq!(totals, SessionUsageTotals::default());
    }

    #[tokio::test]
    async fn save_then_load_round_trips() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage_totals.json");
        let mut totals = SessionUsageTotals::default();
        totals.accumulate(Some(usage(200, 40)));
        save_session_usage_totals(&path, &totals).await;
        let loaded = load_session_usage_totals(&path).await;
        assert_eq!(loaded, totals);
    }

    #[tokio::test]
    async fn main_usage_sink_persists_after_every_call() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage_totals.json");
        let shared = Arc::new(Mutex::new(SessionUsageTotals::default()));
        let sink = MainUsageSink::new(Arc::clone(&shared), Some(path.clone()));

        let first = sink.accumulate(Some(usage(100, 20))).await;
        assert_eq!(first.input_tokens, 100);
        let persisted_after_first = load_session_usage_totals(&path).await;
        assert_eq!(
            persisted_after_first, first,
            "every call should write through to disk"
        );

        let second = sink.accumulate(Some(usage(50, 10))).await;
        assert_eq!(
            second.input_tokens, 150,
            "totals accumulate across calls on the shared Arc"
        );
        let persisted_after_second = load_session_usage_totals(&path).await;
        assert_eq!(persisted_after_second, second);
    }

    #[tokio::test]
    async fn main_usage_sink_with_no_persist_path_still_accumulates_in_memory() {
        let shared = Arc::new(Mutex::new(SessionUsageTotals::default()));
        let sink = MainUsageSink::new(Arc::clone(&shared), None);
        sink.accumulate(Some(usage(10, 5))).await;
        let totals = sink.accumulate(Some(usage(10, 5))).await;
        assert_eq!(
            totals.input_tokens, 20,
            "in-memory accumulation must work without a persist path"
        );
    }

    #[tokio::test]
    async fn main_usage_sink_record_tool_calls_persists_after_every_call() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage_totals.json");
        let shared = Arc::new(Mutex::new(SessionUsageTotals::default()));
        let sink = MainUsageSink::new(Arc::clone(&shared), Some(path.clone()));

        let first = sink.record_tool_calls(3).await;
        assert_eq!(first.tool_calls, 3);
        let persisted_after_first = load_session_usage_totals(&path).await;
        assert_eq!(
            persisted_after_first, first,
            "every tool-call batch should write through to disk"
        );

        let second = sink.record_tool_calls(2).await;
        assert_eq!(
            second.tool_calls, 5,
            "tool call counts accumulate across batches on the shared Arc"
        );
        let persisted_after_second = load_session_usage_totals(&path).await;
        assert_eq!(persisted_after_second, second);
    }
}
