#!/usr/bin/env bash
# Fails when the TypeScript protocol types in web/src/lib/generated differ from
# what the Rust types generate. CI runs this, and `just types-check` runs it
# locally. Fix a failure with `just types`, then commit the result.
#
# The comparison is the working tree against the index: stage regenerated files
# before running it locally.
set -euo pipefail

dir=web/src/lib/generated

# ts-rs writes every file in the directory except the hand-written barrel
# (protocol.ts). Clearing the generated ones first means the file a removed or
# renamed type left behind is not regenerated, so it shows up as a deletion.
grep -rl --include='*.ts' 'This file was generated by \[ts-rs\]' "$dir" | xargs -r rm

cargo test --quiet --test ts_export

# Count files ts-rs newly wrote as changes. Deletions stay unstaged, so they
# show up in the diff too.
git add --intent-to-add --ignore-removal "$dir"

if ! git diff --exit-code -- "$dir"; then
    echo "error: $dir is out of date with the Rust types. Run 'just types' and commit the result." >&2
    exit 1
fi
