//! Cron job execution: runs due jobs and updates their state.

use chrono::NaiveDateTime;
use chrono_tz::Tz;

use crate::agent::Agent;
use crate::agent::context::ProjectsContext;
use crate::channels::null::NullDisplay;
use crate::error::IronclawError;
use crate::models::ModelProvider;

use super::scheduler::compute_next_run_with_backoff;
use super::store::CronStore;
use super::types::{CronJob, CronPayload, Delivery, RunStatus};

/// A notification generated by a cron job for display to the user.
pub struct CronNotification {
    /// Name of the job that produced this notification.
    pub job_name: String,
    /// The display text.
    pub text: String,
}

/// Result of executing due cron jobs.
pub struct CronExecutionResult {
    /// Messages for the memory pipeline.
    pub messages: Vec<crate::models::Message>,
    /// Notifications to display to the user.
    pub notifications: Vec<CronNotification>,
}

/// Execute all due cron jobs.
///
/// The delivery × payload matrix:
/// - `SystemEvent + UserVisible`: queue for next user turn, return notification
/// - `SystemEvent + Background`: return a synthetic user message for the memory pipeline
/// - `AgentTurn + UserVisible`: run ephemeral turn, queue as system event, return notification + messages
/// - `AgentTurn + Background`: run ephemeral turn, return messages for memory pipeline
///
/// If `provider_override` is `Some`, that provider is used for any `AgentTurn`
/// jobs instead of the agent's default provider.
///
/// # Errors
/// Returns `IronclawError` if a store save fails. Individual job failures are
/// recorded in the job's state and do not abort the loop.
pub async fn execute_due_jobs(
    store: &mut CronStore,
    agent: &mut Agent,
    now: NaiveDateTime,
    tz: Tz,
    provider_override: Option<&dyn ModelProvider>,
    projects_ctx: &ProjectsContext<'_>,
) -> Result<CronExecutionResult, IronclawError> {
    let due_ids: Vec<String> = store
        .find_due_jobs(now)
        .iter()
        .map(|j| j.id.clone())
        .collect();

    let mut all_messages: Vec<crate::models::Message> = Vec::new();
    let mut notifications: Vec<CronNotification> = Vec::new();

    for job_id in due_ids {
        // Clone job to avoid borrow conflict with store
        let Some(job) = store.get_job(&job_id).cloned() else {
            continue;
        };

        let (status, error_msg, new_messages, notification) =
            run_job(&job, agent, provider_override, projects_ctx).await;
        if let Some(notif) = notification {
            notifications.push(notif);
        }

        // Update job state
        let Some(job_mut) = store.get_job_mut(&job_id) else {
            continue;
        };

        job_mut.state.last_run_at = Some(now);
        job_mut.state.last_status = Some(status);

        match status {
            RunStatus::Ok => {
                job_mut.state.consecutive_errors = 0;
                job_mut.state.last_error = None;

                // One-shot At job: disable (and delete if requested)
                if matches!(job_mut.schedule, super::types::CronSchedule::At { .. }) {
                    job_mut.enabled = false;
                }
            }
            RunStatus::Error => {
                job_mut.state.consecutive_errors =
                    job_mut.state.consecutive_errors.saturating_add(1);
                job_mut.state.last_error = error_msg;
            }
            RunStatus::Skipped => {}
        }

        // Recompute next_run with backoff applied
        match compute_next_run_with_backoff(job_mut, now, tz) {
            Ok(next) => job_mut.state.next_run_at = next,
            Err(e) => {
                eprintln!("warning: cron job '{job_id}' schedule is invalid, disabling: {e}");
                tracing::warn!(job = %job_id, error = %e, "failed to compute next_run_at, disabling job");
                job_mut.enabled = false;
            }
        }

        all_messages.extend(new_messages);
    }

    // Remove jobs marked for deletion after a successful one-shot run
    let to_delete: Vec<String> = store
        .list_jobs()
        .iter()
        .filter(|j| j.delete_after_run && j.state.last_status == Some(RunStatus::Ok) && !j.enabled)
        .map(|j| j.id.clone())
        .collect();

    for id in to_delete {
        store.remove_job(&id);
    }

    store.save().await?;
    Ok(CronExecutionResult {
        messages: all_messages,
        notifications,
    })
}

/// Run a single cron job, returning status, error, messages, and an optional notification.
async fn run_job(
    job: &CronJob,
    agent: &mut Agent,
    provider_override: Option<&dyn ModelProvider>,
    projects_ctx: &ProjectsContext<'_>,
) -> (
    RunStatus,
    Option<String>,
    Vec<crate::models::Message>,
    Option<CronNotification>,
) {
    match (&job.payload, job.delivery) {
        (CronPayload::SystemEvent { text }, Delivery::UserVisible) => {
            agent.queue_system_event(text.clone());
            let notif = CronNotification {
                job_name: job.name.clone(),
                text: text.clone(),
            };
            (RunStatus::Ok, None, Vec::new(), Some(notif))
        }

        (CronPayload::SystemEvent { text }, Delivery::Background) => {
            tracing::info!(job = %job.name, "background system event: {}", text);
            let msg = crate::models::Message::user(format!("[cron: {}] {}", job.name, text));
            (RunStatus::Ok, None, vec![msg], None)
        }

        (CronPayload::AgentTurn { message }, Delivery::UserVisible) => {
            let display = NullDisplay;
            match agent
                .run_system_turn(message, &display, provider_override, projects_ctx)
                .await
            {
                Ok(result) => {
                    tracing::info!(job = %job.name, "user-visible agent turn completed");
                    let notif = CronNotification {
                        job_name: job.name.clone(),
                        text: result.response.clone(),
                    };
                    agent.queue_system_event(result.response);
                    (RunStatus::Ok, None, result.messages, Some(notif))
                }
                Err(e) => {
                    tracing::warn!(job = %job.name, error = %e, "agent turn failed");
                    (RunStatus::Error, Some(e.to_string()), Vec::new(), None)
                }
            }
        }

        (CronPayload::AgentTurn { message }, Delivery::Background) => {
            let display = NullDisplay;
            match agent
                .run_system_turn(message, &display, provider_override, projects_ctx)
                .await
            {
                Ok(result) => {
                    tracing::info!(job = %job.name, "background agent turn completed");
                    (RunStatus::Ok, None, result.messages, None)
                }
                Err(e) => {
                    tracing::warn!(job = %job.name, error = %e, "agent turn failed");
                    (RunStatus::Error, Some(e.to_string()), Vec::new(), None)
                }
            }
        }
    }
}

/// Initialize `next_run_at` for a newly created job.
///
/// Should be called after adding a job to the store to set the first fire time.
///
/// # Errors
/// Returns `IronclawError::Scheduling` if the schedule cannot be parsed.
pub fn initialize_next_run(
    job: &mut CronJob,
    now: NaiveDateTime,
    tz: Tz,
) -> Result<(), IronclawError> {
    let next = compute_next_run_with_backoff(job, now, tz)?;
    job.state.next_run_at = next;
    Ok(())
}
