<script lang="ts">
  import { formatElapsed, formatTokenCount } from "../lib/format-usage";

  let {
    since = null,
    outputTokens = 0,
    hasUsage = false,
    stopHint = null,
  }: {
    /** `Date.now()` when this turn started, for the live elapsed clock. */
    since?: number | null;
    /** Output tokens generated by every model call so far this turn. */
    outputTokens?: number;
    /** Whether any model call so far this turn reported usage. */
    hasUsage?: boolean;
    /** Trailing hint for the real stop affordance (e.g. "Esc to stop"). */
    stopHint?: string | null;
  } = $props();

  let elapsedMs = $state(0);

  // Ticks once a second so the elapsed time stays live; token progress
  // updates on its own whenever the parent passes a new `outputTokens`.
  $effect(() => {
    if (since === null) {
      elapsedMs = 0;
      return;
    }
    const start = since;
    elapsedMs = Date.now() - start;
    const interval = setInterval(() => {
      elapsedMs = Date.now() - start;
    }, 1000);
    return () => clearInterval(interval);
  });

  let label = $derived.by(() => {
    const parts = [`Thinking… ${formatElapsed(elapsedMs)}`];
    if (hasUsage) parts.push(`↓ ${formatTokenCount(outputTokens)} tokens`);
    if (stopHint) parts.push(stopHint);
    return parts.join(" · ");
  });
</script>

<div class="thinking">
  <span class="thinking-bars">
    <span></span>
    <span></span>
    <span></span>
  </span>
  <span>{label}</span>
</div>
